In [7]:
from lib import read_parquet_user, read_parquet_item, read_parquet_purchase, split_and_save_parquet, build_feature_label

#### Read dataframes

In [8]:
item_df = read_parquet_item('.././Phase-2/preprocessed-dataset/')
item_df.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ age_group ┆ age_grou │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget_fina ┆ _from_des ┆ _final    ┆ p_final_ │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ l         ┆ c_str     ┆ ---       ┆ before   │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ 9M+       ┆ Từ 9M     ┆ Từ 9M    │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ định      ┆           ┆           ┆          │
│ 001029004 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Bé Gái    ┆ null      ┆ Từ 36M    ┆ Từ 36M   │
│ 0150      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆           ┆           ┆          │
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ null      ┆ 0-12M     ┆ 0-12M    │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆           ┆           ┆          │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ null      ┆ ["Từ 4M", ┆ ["Từ     │
│ 0094      ┆ 00        ┆           ┆           ┆   ┆ định      ┆           ┆ "3M-6M",  ┆ 4M",     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "12-36M"] ┆ "3M-6M", │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "12-36M" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ null      ┆ 12-36M    ┆ 12-36M   │
│ 0098      ┆ 00        ┆           ┆           ┆   ┆ định      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
user_df = read_parquet_user('.././Phase-2/preprocessed-dataset/')
user_df.head()

shape: (5, 13)
┌────────────┬────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ gender ┆ location ┆ province   ┆ … ┆ install_da ┆ user_age_ ┆ days_sinc ┆ days_sinc │
│ d          ┆ ---    ┆ ---      ┆ ---        ┆   ┆ tetime     ┆ days      ┆ e_install ┆ e_last_sy │
│ ---        ┆ str    ┆ i32      ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ nc        │
│ i32        ┆        ┆          ┆            ┆   ┆ date       ┆ f64       ┆ f64       ┆ ---       │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆           ┆ f64       │
╞════════════╪════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1800754    ┆ female ┆ 169      ┆ Hồ Chí     ┆ … ┆ 2018-09-08 ┆ 2579.1641 ┆ 2579.9170 ┆ 76.419849 │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆ 9         ┆ 91        ┆           │
│ 1800755    ┆ female ┆ 822      ┆ Lâm Đồng   ┆ … ┆ 2018-09-08 ┆ 2579.1638 ┆ 2579.9170 ┆ 76.419849 │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 91        ┆           │
│ 1619184    ┆ male   ┆ 980      ┆ Cần Thơ    ┆ … ┆ 2018-06-09 ┆ 2670.2372 ┆ 2670.9170 ┆ null      │
│            ┆        ┆          ┆            ┆   ┆            ┆ 16        ┆ 91        ┆           │
│ 1800766    ┆ female ┆ 591      ┆ Đồng Nai   ┆ … ┆ 2018-09-08 ┆ 2579.1610 ┆ 2579.9170 ┆ 76.419849 │
│            ┆        ┆          ┆            ┆   ┆            ┆ 78        ┆ 91        ┆           │
│ 1800777    ┆ female ┆ 971      ┆ Hồ Chí     ┆ … ┆ 2018-09-08 ┆ 2579.1579 ┆ 2579.9170 ┆ 76.419849 │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆ 04        ┆ 91        ┆           │
└────────────┴────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [10]:
transaction_df = read_parquet_purchase('.././Phase-2/preprocessed-dataset/')
transaction_df.head()

shape: (5, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ price     ┆ quantity ┆ customer_ ┆ … ┆ discount  ┆ list_pric ┆ category_ ┆ discount_ │
│ ---       ┆ ---       ┆ ---      ┆ id        ┆   ┆ ---       ┆ e         ┆ l2        ┆ rate      │
│ str       ┆ decimal[3 ┆ i32      ┆ ---       ┆   ┆ decimal[3 ┆ ---       ┆ ---       ┆ ---       │
│           ┆ 8,4]      ┆          ┆ i32       ┆   ┆ 8,4]      ┆ decimal[3 ┆ str       ┆ decimal[3 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8,4]      ┆           ┆ 8,4]      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 259600000 ┆ 296000.00 ┆ 1        ┆ 7627794   ┆ … ┆ 149000.00 ┆ 445000.00 ┆ Moony     ┆ 0.3348    │
│ 0003      ┆ 00        ┆          ┆           ┆   ┆ 00        ┆ 00        ┆           ┆           │
│ 151200000 ┆ 274349.00 ┆ 1        ┆ 7367484   ┆ … ┆ 20651.000 ┆ 295000.00 ┆ TPCN cho  ┆ 0.0700    │
│ 0004      ┆ 00        ┆          ┆           ┆   ┆ 0         ┆ 00        ┆ bé        ┆           │
│ 553700000 ┆ 70562.000 ┆ 1        ┆ 4795945   ┆ … ┆ 4438.0000 ┆ 75000.000 ┆ Snack ăn  ┆ 0.0592    │
│ 0015      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ dặm       ┆           │
│ 464400000 ┆ 58240.000 ┆ 4        ┆ 7253028   ┆ … ┆ 23040.000 ┆ 65000.000 ┆ Caryn     ┆ 0.1040    │
│ 0001      ┆ 0         ┆          ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│ 270000000 ┆ 61750.000 ┆ 1        ┆ 7681758   ┆ … ┆ 3250.0000 ┆ 65000.000 ┆ Khăn khô  ┆ 0.0500    │
│ 0002      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
transaction_df = transaction_df.sort("created_date")  # mặc định tăng dần theo thời gian
transaction_df.head()

shape: (5, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ price     ┆ quantity ┆ customer_ ┆ … ┆ discount  ┆ list_pric ┆ category_ ┆ discount_ │
│ ---       ┆ ---       ┆ ---      ┆ id        ┆   ┆ ---       ┆ e         ┆ l2        ┆ rate      │
│ str       ┆ decimal[3 ┆ i32      ┆ ---       ┆   ┆ decimal[3 ┆ ---       ┆ ---       ┆ ---       │
│           ┆ 8,4]      ┆          ┆ i32       ┆   ┆ 8,4]      ┆ decimal[3 ┆ str       ┆ decimal[3 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8,4]      ┆           ┆ 8,4]      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 177400000 ┆ 44000.000 ┆ 1        ┆ 3171058   ┆ … ┆ 0.0000    ┆ 44000.000 ┆ Khăn ướt  ┆ 0.0000    │
│ 0003      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆           ┆           │
│ 535800000 ┆ 40000.000 ┆ 1        ┆ 3169607   ┆ … ┆ 0.0000    ┆ 40000.000 ┆ Bánh &    ┆ 0.0000    │
│ 0002      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ Kẹo cho   ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ bé        ┆           │
│ 709200000 ┆ 99000.000 ┆ 1        ┆ 3976155   ┆ … ┆ 0.0000    ┆ 99000.000 ┆ Bánh &    ┆ 0.0000    │
│ 0011      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ Kẹo cho   ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ bé        ┆           │
│ 226100000 ┆ 289000.00 ┆ 1        ┆ 2469962   ┆ … ┆ 71000.000 ┆ 360000.00 ┆ Huggies   ┆ 0.1972    │
│ 0005      ┆ 00        ┆          ┆           ┆   ┆ 0         ┆ 00        ┆           ┆           │
│ 454600000 ┆ 117600.00 ┆ 1        ┆ 3610359   ┆ … ┆ 0.0000    ┆ 183000.00 ┆ Bánh      ┆ 0.3574    │
│ 0001      ┆ 00        ┆          ┆           ┆   ┆           ┆ 00        ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Train data

In [12]:
from datetime import datetime

begin_hist = datetime(2024, 1, 1)
end_hist = datetime(2024, 10, 31)   # 30/09/2024, không phải 31/09
begin_recent = datetime(2024, 11, 1)
end_recent = datetime(2024, 11, 30)

feature_label_lf = build_feature_label(
    transactions_lf=transaction_df.lazy(),   # convert DataFrame -> LazyFrame
    items_lf=item_df.lazy(),
    users_lf=user_df.lazy(),
    begin=begin_hist,
    end=end_hist,
    begin_recent=begin_recent,
    end_recent=end_recent,
)

feature_label_df = feature_label_lf.collect()
feature_label_df.head()

shape: (5, 6)
┌─────────────┬───────────────┬─────────────┬─────────────────┬────────────────┬─────┐
│ customer_id ┆ item_id       ┆ brand_count ┆ age_group_count ┆ category_count ┆ Y   │
│ ---         ┆ ---           ┆ ---         ┆ ---             ┆ ---            ┆ --- │
│ i32         ┆ str           ┆ u32         ┆ u32             ┆ u32            ┆ i8  │
╞═════════════╪═══════════════╪═════════════╪═════════════════╪════════════════╪═════╡
│ 7773659     ┆ 2070000000026 ┆ 1           ┆ 1               ┆ 1              ┆ 0   │
│ 7586536     ┆ 5856000000001 ┆ 1           ┆ 1               ┆ 1              ┆ 0   │
│ 2756479     ┆ 1535000000004 ┆ 1           ┆ 19              ┆ 1              ┆ 0   │
│ 96901       ┆ 3880000000001 ┆ 1           ┆ 3               ┆ 1              ┆ 0   │
│ 6861830     ┆ 3362000000069 ┆ 7           ┆ 2               ┆ 2              ┆ 0   │
└─────────────┴───────────────┴─────────────┴─────────────────┴────────────────┴─────┘

In [13]:
feature_label_df['Y'].value_counts()

shape: (2, 2)
┌─────┬──────────┐
│ Y   ┆ count    │
│ --- ┆ ---      │
│ i8  ┆ u32      │
╞═════╪══════════╡
│ 0   ┆ 20023647 │
│ 1   ┆ 2749181  │
└─────┴──────────┘

Xử lý negative samples bằng kỹ thuật negative downsampling

In [14]:
df = feature_label_df

In [15]:
import polars as pl

# Tách positive và negative
df_pos = df.filter(pl.col("Y") == 1) 
df_neg = df.filter(pl.col("Y") == 0) 
pos_count = df_pos.height 
neg_target = pos_count * 2 
# tỉ lệ 1:2 
print("Positive =", pos_count) 
print("Negative target =", neg_target) 
# Lấy ngẫu nhiên neg_target mẫu từ negatives 
df_neg_sampled = df_neg.sample(n=neg_target, shuffle=True) 
# Gộp lại 
train_data = pl.concat([df_pos, df_neg_sampled]).sample(fraction=1.0, shuffle=True) 
print(train_data.shape) 
train_data.head()

Positive = 2749181
Negative target = 5498362
(8247543, 6)

shape: (5, 6)
┌─────────────┬───────────────┬─────────────┬─────────────────┬────────────────┬─────┐
│ customer_id ┆ item_id       ┆ brand_count ┆ age_group_count ┆ category_count ┆ Y   │
│ ---         ┆ ---           ┆ ---         ┆ ---             ┆ ---            ┆ --- │
│ i32         ┆ str           ┆ u32         ┆ u32             ┆ u32            ┆ i8  │
╞═════════════╪═══════════════╪═════════════╪═════════════════╪════════════════╪═════╡
│ 5873987     ┆ 1236000000002 ┆ 1           ┆ 1               ┆ 1              ┆ 0   │
│ 4612062     ┆ 1771000000002 ┆ 0           ┆ 0               ┆ 0              ┆ 1   │
│ 6922405     ┆ 2700000000002 ┆ 1           ┆ 6               ┆ 1              ┆ 0   │
│ 7979364     ┆ 3773000000004 ┆ 2           ┆ 2               ┆ 2              ┆ 1   │
│ 3907646     ┆ 2766000000005 ┆ 1           ┆ 5               ┆ 1              ┆ 0   │
└─────────────┴───────────────┴─────────────┴─────────────────┴────────────────┴─────┘

In [16]:
train_data['Y'].value_counts()

shape: (2, 2)
┌─────┬─────────┐
│ Y   ┆ count   │
│ --- ┆ ---     │
│ i8  ┆ u32     │
╞═════╪═════════╡
│ 0   ┆ 5498362 │
│ 1   ┆ 2749181 │
└─────┴─────────┘

In [17]:
split_and_save_parquet(train_data, 1, "./", "train")

Đã lưu file: ./sale_pers.train_data_0.parquet

#### Evaluate data

In [18]:
from datetime import datetime

begin_hist = datetime(2024, 1, 1)
end_hist = datetime(2024, 11, 30)
begin_recent = datetime(2024, 12, 1)
end_recent = datetime(2024, 12, 31)

feature_label_lf = build_feature_label(
    transactions_lf=transaction_df.lazy(),   # convert DataFrame -> LazyFrame
    items_lf=item_df.lazy(),
    users_lf=user_df.lazy(),
    begin=begin_hist,
    end=end_hist,
    begin_recent=begin_recent,
    end_recent=end_recent,
)

feature_label_df = feature_label_lf.collect()
feature_label_df.head()

shape: (5, 6)
┌─────────────┬───────────────┬─────────────┬─────────────────┬────────────────┬─────┐
│ customer_id ┆ item_id       ┆ brand_count ┆ age_group_count ┆ category_count ┆ Y   │
│ ---         ┆ ---           ┆ ---         ┆ ---             ┆ ---            ┆ --- │
│ i32         ┆ str           ┆ u32         ┆ u32             ┆ u32            ┆ i8  │
╞═════════════╪═══════════════╪═════════════╪═════════════════╪════════════════╪═════╡
│ 5637568     ┆ 2263000000015 ┆ 2           ┆ 4               ┆ 2              ┆ 0   │
│ 775334      ┆ 4876000000003 ┆ 0           ┆ 10              ┆ 0              ┆ 1   │
│ 7390322     ┆ 4459000000003 ┆ 1           ┆ 1               ┆ 1              ┆ 0   │
│ 1727700     ┆ 4853000000009 ┆ 1           ┆ 5               ┆ 1              ┆ 0   │
│ 527171      ┆ 0175000000008 ┆ 1           ┆ 2               ┆ 1              ┆ 0   │
└─────────────┴───────────────┴─────────────┴─────────────────┴────────────────┴─────┘

In [19]:
feature_label_df['Y'].value_counts()

shape: (2, 2)
┌─────┬──────────┐
│ Y   ┆ count    │
│ --- ┆ ---      │
│ i8  ┆ u32      │
╞═════╪══════════╡
│ 1   ┆ 2684720  │
│ 0   ┆ 22015879 │
└─────┴──────────┘

In [20]:
df = feature_label_df

In [21]:
import polars as pl

# Tách positive và negative
df_pos = df.filter(pl.col("Y") == 1)
df_neg = df.filter(pl.col("Y") == 0)

print("Eval POS (Y=1)  =", df_pos.height)
print("Eval NEG (Y=0)  =", df_neg.height)

# Số negative tối đa mỗi user trong eval
MAX_NEG_PER_USER = 100  # bạn có thể chỉnh: 50, 100, 200,...

# 1) Shuffle toàn bộ negative trước cho random
df_neg_shuffled = df_neg.sample(
    fraction=1.0,
    shuffle=True,
    seed=42,
)

# 2) Với mỗi customer_id, lấy tối đa MAX_NEG_PER_USER negative
df_neg_sampled = (
    df_neg_shuffled
    .group_by("customer_id")
    .head(MAX_NEG_PER_USER)
)

print("Eval NEG sampled (per user, ≤ MAX_NEG_PER_USER) =", df_neg_sampled.height)

# 3) Gộp lại: TẤT CẢ positive + negative đã sample per user
eval_data = pl.concat([df_pos, df_neg_sampled])

# 4) Shuffle toàn bộ eval_data lần nữa cho ngẫu nhiên
eval_data = eval_data.sample(
    fraction=1.0,
    shuffle=True,
    seed=42,
)

print("Eval_data shape:", eval_data.shape)
eval_data.head()

Eval POS (Y=1)  = 2684720
Eval NEG (Y=0)  = 22015879
Eval NEG sampled (per user, ≤ MAX_NEG_PER_USER) = 21736071
Eval_data shape: (24420791, 6)

shape: (5, 6)
┌─────────────┬───────────────┬─────────────┬─────────────────┬────────────────┬─────┐
│ customer_id ┆ item_id       ┆ brand_count ┆ age_group_count ┆ category_count ┆ Y   │
│ ---         ┆ ---           ┆ ---         ┆ ---             ┆ ---            ┆ --- │
│ i32         ┆ str           ┆ u32         ┆ u32             ┆ u32            ┆ i8  │
╞═════════════╪═══════════════╪═════════════╪═════════════════╪════════════════╪═════╡
│ 6586884     ┆ 0007130000025 ┆ 1           ┆ 2               ┆ 1              ┆ 0   │
│ 8002049     ┆ 2691000000001 ┆ 0           ┆ 14              ┆ 0              ┆ 1   │
│ 7321965     ┆ 0029040000008 ┆ 1           ┆ 4               ┆ 1              ┆ 0   │
│ 7062633     ┆ 1331000000004 ┆ 1           ┆ 18              ┆ 1              ┆ 0   │
│ 3652809     ┆ 5826000000005 ┆ 2           ┆ 16              ┆ 2              ┆ 0   │
└─────────────┴───────────────┴─────────────┴─────────────────┴────────────────┴─────┘

In [22]:
split_and_save_parquet(eval_data, 1, "./", "eva")

Đã lưu file: ./sale_pers.eva_data_0.parquet