In [35]:
from lib import read_parquet_user, read_parquet_item, read_parquet_purchase, split_and_save_parquet, build_feature_label

#### Read dataframes

In [36]:
item_df = read_parquet_item('.././preprocessed-feature/')
item_df.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category  ┆ … ┆ item_type ┆ sale_stat ┆ age_bucke ┆ price_no │
│ ---       ┆ ---       ┆ l1        ┆ ---       ┆   ┆ _final    ┆ us        ┆ t_final   ┆ rm       │
│ str       ┆ decimal[3 ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆           ┆   ┆ str       ┆ i32       ┆ str       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 050202000 ┆ 99000.000 ┆ babycare  ┆ núm ty dr ┆ … ┆ null      ┆ 0         ┆ 0-6m      ┆ -0.17893 │
│ 0004      ┆ 0         ┆           ┆ brown     ┆   ┆           ┆           ┆           ┆ 3        │
│ 001029004 ┆ 69000.000 ┆ thời      ┆ bộ quần   ┆ … ┆ bộ quần   ┆ 0         ┆ 2-4y      ┆ -0.23762 │
│ 0150      ┆ 0         ┆ trang     ┆ áo bé gái ┆   ┆ áo        ┆           ┆           ┆ 7        │
│ 000801000 ┆ 45000.000 ┆ đồ chơi & ┆ gặm nướu  ┆ … ┆ null      ┆ 0         ┆ 1-4y      ┆ -0.28458 │
│ 0015      ┆ 0         ┆ sách      ┆ khác      ┆   ┆           ┆           ┆           ┆ 2        │
│ 002001000 ┆ 401000.00 ┆ tã        ┆ merries_s ┆ … ┆ null      ┆ 0         ┆ 0-6m      ┆ 0.411922 │
│ 0094      ┆ 00        ┆           ┆ ơ sinh    ┆   ┆           ┆           ┆           ┆          │
│ 002001000 ┆ 401000.00 ┆ tã        ┆ merries_t ┆ … ┆ null      ┆ 0         ┆ 6-12m     ┆ 0.411922 │
│ 0098      ┆ 00        ┆           ┆ ã quần    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [37]:
user_df = read_parquet_user('.././preprocessed-feature/')
user_df.head()

shape: (5, 11)
┌────────────┬────────┬──────────┬────────────┬───┬────────────┬──────────┬────────────┬───────────┐
│ customer_i ┆ gender ┆ location ┆ province   ┆ … ┆ install_ap ┆ district ┆ milk_segme ┆ diaper_se │
│ d          ┆ ---    ┆ ---      ┆ ---        ┆   ┆ p          ┆ ---      ┆ nt_prefere ┆ gment_pre │
│ ---        ┆ str    ┆ i32      ┆ str        ┆   ┆ ---        ┆ str      ┆ nce        ┆ ference   │
│ i32        ┆        ┆          ┆            ┆   ┆ str        ┆          ┆ ---        ┆ ---       │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ i64        ┆ i64       │
╞════════════╪════════╪══════════╪════════════╪═══╪════════════╪══════════╪════════════╪═══════════╡
│ 2102259    ┆ Nữ     ┆ 838      ┆ Kiên Giang ┆ … ┆ In-Store   ┆ Gò Quao  ┆ null       ┆ null      │
│ 2102190    ┆ Nữ     ┆ 728      ┆ Gia Lai    ┆ … ┆ In-Store   ┆ Pleiku   ┆ null       ┆ 2         │
│ 2102266    ┆ Nữ     ┆ 535      ┆ Đồng Nai   ┆ … ┆ In-Store   ┆ Biên Hòa ┆ null       ┆ null      │
│ 2102268    ┆ Nam    ┆ 545      ┆ Hồ Chí     ┆ … ┆ In-Store   ┆ Tân Bình ┆ null       ┆ null      │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆          ┆            ┆           │
│ 2102273    ┆ Nữ     ┆ 365      ┆ Hồ Chí     ┆ … ┆ In-Store   ┆ Củ Chi   ┆ null       ┆ null      │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆          ┆            ┆           │
└────────────┴────────┴──────────┴────────────┴───┴────────────┴──────────┴────────────┴───────────┘

In [38]:
transaction_df = read_parquet_purchase('.././preprocessed-feature/')
transaction_df.head()

shape: (5, 18)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ quantity ┆ customer_ ┆ created_d ┆ … ┆ avg_trans ┆ segment_n ┆ avg_cat_l ┆ segment_n │
│ ---       ┆ ---      ┆ id        ┆ ate       ┆   ┆ action_am ┆ ame       ┆ 1_per_pur ┆ ame_right │
│ str       ┆ i32      ┆ ---       ┆ ---       ┆   ┆ ount_per_ ┆ ---       ┆ chase     ┆ ---       │
│           ┆          ┆ i32       ┆ datetime[ ┆   ┆ pur…      ┆ str       ┆ ---       ┆ str       │
│           ┆          ┆           ┆ μs]       ┆   ┆ ---       ┆           ┆ f64       ┆           │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 280300000 ┆ 2        ┆ 6604637   ┆ 2024-10-1 ┆ … ┆ 580106.15 ┆ Trung cấp ┆ 1.686047  ┆ Mua vừa   │
│ 0013      ┆          ┆           ┆ 4 18:02:1 ┆   ┆ 3069      ┆           ┆           ┆           │
│           ┆          ┆           ┆ 5.860     ┆   ┆           ┆           ┆           ┆           │
│ 002002000 ┆ 1        ┆ 6594820   ┆ 2024-10-1 ┆ … ┆ 274824.47 ┆ Bình dân  ┆ 1.895522  ┆ Mua vừa   │
│ 0172      ┆          ┆           ┆ 4 07:37:3 ┆   ┆ 673       ┆           ┆           ┆           │
│           ┆          ┆           ┆ 9.637     ┆   ┆           ┆           ┆           ┆           │
│ 002012000 ┆ 1        ┆ 7957733   ┆ 2024-10-1 ┆ … ┆ 495850.0  ┆ Trung cấp ┆ 4.0       ┆ Mua nhiều │
│ 0014      ┆          ┆           ┆ 4 14:50:2 ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 8.070     ┆   ┆           ┆           ┆           ┆           │
│ 177100000 ┆ 1        ┆ 7559596   ┆ 2024-10-1 ┆ … ┆ 352361.47 ┆ Bình dân  ┆ 1.222222  ┆ Mua ít    │
│ 0002      ┆          ┆           ┆ 4 12:13:4 ┆   ┆ 8357      ┆           ┆           ┆           │
│           ┆          ┆           ┆ 0.113     ┆   ┆           ┆           ┆           ┆           │
│ 130800000 ┆ 2        ┆ 6885875   ┆ 2024-10-1 ┆ … ┆ 384639.61 ┆ Bình dân  ┆ 1.571429  ┆ Mua vừa   │
│ 0003      ┆          ┆           ┆ 4 16:20:1 ┆   ┆ 9569      ┆           ┆           ┆           │
│           ┆          ┆           ┆ 3.623     ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [39]:
transaction_df = transaction_df.sort("created_date")  # mặc định tăng dần theo thời gian
transaction_df.head()

shape: (5, 18)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ quantity ┆ customer_ ┆ created_d ┆ … ┆ avg_trans ┆ segment_n ┆ avg_cat_l ┆ segment_n │
│ ---       ┆ ---      ┆ id        ┆ ate       ┆   ┆ action_am ┆ ame       ┆ 1_per_pur ┆ ame_right │
│ str       ┆ i32      ┆ ---       ┆ ---       ┆   ┆ ount_per_ ┆ ---       ┆ chase     ┆ ---       │
│           ┆          ┆ i32       ┆ datetime[ ┆   ┆ pur…      ┆ str       ┆ ---       ┆ str       │
│           ┆          ┆           ┆ μs]       ┆   ┆ ---       ┆           ┆ f64       ┆           │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 200600000 ┆ 1        ┆ 4689434   ┆ 2024-01-0 ┆ … ┆ 1.1825e6  ┆ Trung cấp ┆ 1.378641  ┆ Mua ít    │
│ 0006      ┆          ┆           ┆ 1 06:44:5 ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 9.037     ┆   ┆           ┆           ┆           ┆           │
│ 002001000 ┆ 1        ┆ 5279260   ┆ 2024-01-0 ┆ … ┆ 465000.0  ┆ Trung cấp ┆ 1.0       ┆ Mua ít    │
│ 0440      ┆          ┆           ┆ 1 06:48:2 ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ 8.537     ┆   ┆           ┆           ┆           ┆           │
│ 248500000 ┆ 1        ┆ 4190229   ┆ 2024-01-0 ┆ … ┆ 511970.68 ┆ Trung cấp ┆ 1.162791  ┆ Mua ít    │
│ 0004      ┆          ┆           ┆ 1 06:49:3 ┆   ┆ 006       ┆           ┆           ┆           │
│           ┆          ┆           ┆ 2.443     ┆   ┆           ┆           ┆           ┆           │
│ 248200000 ┆ 1        ┆ 6530105   ┆ 2024-01-0 ┆ … ┆ 339501.96 ┆ Bình dân  ┆ 1.631579  ┆ Mua vừa   │
│ 0004      ┆          ┆           ┆ 1 06:51:1 ┆   ┆ 5496      ┆           ┆           ┆           │
│           ┆          ┆           ┆ 1.120     ┆   ┆           ┆           ┆           ┆           │
│ 676700000 ┆ 1        ┆ 6393411   ┆ 2024-01-0 ┆ … ┆ 386749.06 ┆ Bình dân  ┆ 1.705882  ┆ Mua vừa   │
│ 0003      ┆          ┆           ┆ 1 06:52:4 ┆   ┆ 8627      ┆           ┆           ┆           │
│           ┆          ┆           ┆ 8.570     ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Train data

In [40]:
from datetime import datetime

begin_hist = datetime(2024, 1, 1)
end_hist = datetime(2024, 11, 30)   # 30/09/2024, không phải 31/09
begin_recent = datetime(2024, 11, 1)
end_recent = datetime(2024, 11, 30)

feature_label_lf = build_feature_label(
    transactions_lf=transaction_df.lazy(),   # convert DataFrame -> LazyFrame
    items_lf=item_df.lazy(),
    users_lf=user_df.lazy(),
    begin_hist=begin_hist,
    end_hist=end_hist,
    begin_recent=begin_recent,
    end_recent=end_recent,
)

feature_label_df = feature_label_lf.collect()
feature_label_df.head()

shape: (5, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────┐
│ customer_i ┆ item_id    ┆ brand_coun ┆ age_counts ┆ … ┆ segment_co ┆ target_us ┆ time_sinc ┆ Y   │
│ d          ┆ ---        ┆ ts         ┆ ---        ┆   ┆ unts       ┆ er_group_ ┆ e_last_pu ┆ --- │
│ ---        ┆ str        ┆ ---        ┆ u32        ┆   ┆ ---        ┆ counts    ┆ rchase_in ┆ i8  │
│ i32        ┆            ┆ u32        ┆            ┆   ┆ u32        ┆ ---       ┆ _B_…      ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆ u32       ┆ ---       ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ i64       ┆     │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════╡
│ 6407110    ┆ 6697000000 ┆ 5          ┆ 5          ┆ … ┆ 0          ┆ 5         ┆ 186       ┆ 0   │
│            ┆ 002        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 4942290    ┆ 3787000000 ┆ 1          ┆ 3          ┆ … ┆ 3          ┆ 9         ┆ 208       ┆ 0   │
│            ┆ 014        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 6439082    ┆ 7175000000 ┆ 6          ┆ 25         ┆ … ┆ 0          ┆ 19        ┆ 10        ┆ 1   │
│            ┆ 002        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 4800647    ┆ 5858000000 ┆ 1          ┆ 0          ┆ … ┆ 0          ┆ 2         ┆ 54        ┆ 0   │
│            ┆ 003        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 6046244    ┆ 1371000000 ┆ 7          ┆ 10         ┆ … ┆ 0          ┆ 7         ┆ 240       ┆ 0   │
│            ┆ 001        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────┘

In [41]:
feature_label_df['Y'].value_counts()

shape: (2, 2)
┌─────┬──────────┐
│ Y   ┆ count    │
│ --- ┆ ---      │
│ i8  ┆ u32      │
╞═════╪══════════╡
│ 0   ┆ 20039733 │
│ 1   ┆ 2659290  │
└─────┴──────────┘

Xử lý negative samples bằng kỹ thuật negative downsampling

In [42]:
df = feature_label_df

In [43]:
import polars as pl

# Tách positive và negative
df_pos = df.filter(pl.col("Y") == 1) 
df_neg = df.filter(pl.col("Y") == 0) 
pos_count = df_pos.height 
neg_target = pos_count * 2 
# tỉ lệ 1:2 
print("Positive =", pos_count) 
print("Negative target =", neg_target) 
# Lấy ngẫu nhiên neg_target mẫu từ negatives 
df_neg_sampled = df_neg.sample(n=neg_target, shuffle=True) 
# Gộp lại 
train_data = pl.concat([df_pos, df_neg_sampled]).sample(fraction=1.0, shuffle=True) 
print(train_data.shape) 
train_data.head()

Positive = 2659290
Negative target = 5318580
(7977870, 9)

shape: (5, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────┐
│ customer_i ┆ item_id    ┆ brand_coun ┆ age_counts ┆ … ┆ segment_co ┆ target_us ┆ time_sinc ┆ Y   │
│ d          ┆ ---        ┆ ts         ┆ ---        ┆   ┆ unts       ┆ er_group_ ┆ e_last_pu ┆ --- │
│ ---        ┆ str        ┆ ---        ┆ u32        ┆   ┆ ---        ┆ counts    ┆ rchase_in ┆ i8  │
│ i32        ┆            ┆ u32        ┆            ┆   ┆ u32        ┆ ---       ┆ _B_…      ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆ u32       ┆ ---       ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ i64       ┆     │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════╡
│ 1923522    ┆ 5444000000 ┆ 3          ┆ 56         ┆ … ┆ 0          ┆ 81        ┆ 196       ┆ 0   │
│            ┆ 011        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 5582484    ┆ 6357000000 ┆ 7          ┆ 12         ┆ … ┆ 0          ┆ 17        ┆ 12        ┆ 1   │
│            ┆ 002        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 5726182    ┆ 4396000000 ┆ 6          ┆ 15         ┆ … ┆ 23         ┆ 14        ┆ 20        ┆ 1   │
│            ┆ 002        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 7869009    ┆ 2263000000 ┆ 3          ┆ 30         ┆ … ┆ 0          ┆ 17        ┆ 3         ┆ 1   │
│            ┆ 021        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 7007188    ┆ 0135000000 ┆ 1          ┆ 1          ┆ … ┆ 4          ┆ 4         ┆ 130       ┆ 0   │
│            ┆ 001        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────┘

In [44]:
train_data['Y'].value_counts()

shape: (2, 2)
┌─────┬─────────┐
│ Y   ┆ count   │
│ --- ┆ ---     │
│ i8  ┆ u32     │
╞═════╪═════════╡
│ 0   ┆ 5318580 │
│ 1   ┆ 2659290 │
└─────┴─────────┘

In [45]:
split_and_save_parquet(train_data, 1, "./", "train")

Đã lưu file: ./sale_pers.train_data_0.parquet

#### Evaluate data

In [46]:
from datetime import datetime

begin_hist = datetime(2024, 1, 1)
end_hist = datetime(2024, 12, 31)
begin_recent = datetime(2024, 12, 1)
end_recent = datetime(2024, 12, 31)

feature_label_lf = build_feature_label(
    transactions_lf=transaction_df.lazy(),   # convert DataFrame -> LazyFrame
    items_lf=item_df.lazy(),
    users_lf=user_df.lazy(),
    begin_hist=begin_hist,
    end_hist=end_hist,
    begin_recent=begin_recent,
    end_recent=end_recent,
)

feature_label_df = feature_label_lf.collect()
feature_label_df.head()

shape: (5, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────┐
│ customer_i ┆ item_id    ┆ brand_coun ┆ age_counts ┆ … ┆ segment_co ┆ target_us ┆ time_sinc ┆ Y   │
│ d          ┆ ---        ┆ ts         ┆ ---        ┆   ┆ unts       ┆ er_group_ ┆ e_last_pu ┆ --- │
│ ---        ┆ str        ┆ ---        ┆ u32        ┆   ┆ ---        ┆ counts    ┆ rchase_in ┆ i8  │
│ i32        ┆            ┆ u32        ┆            ┆   ┆ u32        ┆ ---       ┆ _B_…      ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆ u32       ┆ ---       ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ i64       ┆     │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════╡
│ 6711143    ┆ 2278000000 ┆ 4          ┆ 2          ┆ … ┆ 8          ┆ 15        ┆ 126       ┆ 0   │
│            ┆ 028        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 628682     ┆ 6501000000 ┆ 7          ┆ 15         ┆ … ┆ 21         ┆ 19        ┆ 250       ┆ 0   │
│            ┆ 002        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 6067581    ┆ 1396000000 ┆ 1          ┆ 4          ┆ … ┆ 12         ┆ 9         ┆ 276       ┆ 0   │
│            ┆ 020        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 3647946    ┆ 6792000000 ┆ 2          ┆ 41         ┆ … ┆ 69         ┆ 24        ┆ 179       ┆ 0   │
│            ┆ 004        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 7166679    ┆ 5420000000 ┆ 99         ┆ 112        ┆ … ┆ 138        ┆ 68        ┆ 135       ┆ 0   │
│            ┆ 002        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────┘

In [47]:
feature_label_df['Y'].value_counts()

shape: (2, 2)
┌─────┬──────────┐
│ Y   ┆ count    │
│ --- ┆ ---      │
│ i8  ┆ u32      │
╞═════╪══════════╡
│ 1   ┆ 2609159  │
│ 0   ┆ 22031908 │
└─────┴──────────┘

In [48]:
df = feature_label_df

In [49]:
import polars as pl

# Tách positive và negative
df_pos = df.filter(pl.col("Y") == 1)
df_neg = df.filter(pl.col("Y") == 0)

print("Eval POS (Y=1)  =", df_pos.height)
print("Eval NEG (Y=0)  =", df_neg.height)

# Số negative tối đa mỗi user trong eval
MAX_NEG_PER_USER = 100  # bạn có thể chỉnh: 50, 100, 200,...

# 1) Shuffle toàn bộ negative trước cho random
df_neg_shuffled = df_neg.sample(
    fraction=1.0,
    shuffle=True,
    seed=42,
)

# 2) Với mỗi customer_id, lấy tối đa MAX_NEG_PER_USER negative
df_neg_sampled = (
    df_neg_shuffled
    .group_by("customer_id")
    .head(MAX_NEG_PER_USER)
)

print("Eval NEG sampled (per user, ≤ MAX_NEG_PER_USER) =", df_neg_sampled.height)

# 3) Gộp lại: TẤT CẢ positive + negative đã sample per user
eval_data = pl.concat([df_pos, df_neg_sampled])

# 4) Shuffle toàn bộ eval_data lần nữa cho ngẫu nhiên
eval_data = eval_data.sample(
    fraction=1.0,
    shuffle=True,
    seed=42,
)

print("Eval_data shape:", eval_data.shape)
eval_data.head()

Eval POS (Y=1)  = 2609159
Eval NEG (Y=0)  = 22031908
Eval NEG sampled (per user, ≤ MAX_NEG_PER_USER) = 21750285
Eval_data shape: (24359444, 9)

shape: (5, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────┐
│ customer_i ┆ item_id    ┆ brand_coun ┆ age_counts ┆ … ┆ segment_co ┆ target_us ┆ time_sinc ┆ Y   │
│ d          ┆ ---        ┆ ts         ┆ ---        ┆   ┆ unts       ┆ er_group_ ┆ e_last_pu ┆ --- │
│ ---        ┆ str        ┆ ---        ┆ u32        ┆   ┆ ---        ┆ counts    ┆ rchase_in ┆ i8  │
│ i32        ┆            ┆ u32        ┆            ┆   ┆ u32        ┆ ---       ┆ _B_…      ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆ u32       ┆ ---       ┆     │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ i64       ┆     │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════╡
│ 3511493    ┆ 0954000000 ┆ 2          ┆ 2          ┆ … ┆ 2          ┆ 2         ┆ 200       ┆ 0   │
│            ┆ 044        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 1841305    ┆ 4895000000 ┆ 3          ┆ 36         ┆ … ┆ 14         ┆ 25        ┆ 2         ┆ 1   │
│            ┆ 001        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 5012844    ┆ 5951000000 ┆ 3          ┆ 5          ┆ … ┆ 2          ┆ 11        ┆ 33        ┆ 0   │
│            ┆ 002        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 5248629    ┆ 0020020000 ┆ 1          ┆ 0          ┆ … ┆ 0          ┆ 2         ┆ 267       ┆ 0   │
│            ┆ 185        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
│ 7225919    ┆ 4013000000 ┆ 10         ┆ 4          ┆ … ┆ 0          ┆ 26        ┆ 126       ┆ 0   │
│            ┆ 041        ┆            ┆            ┆   ┆            ┆           ┆           ┆     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────┘

In [50]:
split_and_save_parquet(eval_data, 1, "./", "eva")

Đã lưu file: ./sale_pers.eva_data_0.parquet