In [2]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
def read_parquet_transaction(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    purchase_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    purchase_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_chunk_files]) if purchase_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return purchase_chunk_df

In [4]:
def read_parquet_item(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    item_chunk_files = [file for file in files if 'item_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return item_chunk_df

In [5]:
item = read_parquet_item('dataset')
item.head()

shape: (5, 34)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ volume    ┆ material  ┆ sale_stat ┆ descripti │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ ---       ┆ ---       ┆ us        ┆ on_new    │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆           ┆           ┆ i32       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 004        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không xác │
│       ┆ 150        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ định      │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 015        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 094        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 098        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
trans = read_parquet_transaction("./preprocessed_01-2025")
trans.head()

shape: (5, 13)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ price     ┆ quantity ┆ customer_ ┆ … ┆ category_ ┆ list_pric ┆ category_ ┆ discount_ │
│ ---       ┆ ---       ┆ ---      ┆ id        ┆   ┆ l1        ┆ e         ┆ l2        ┆ rate      │
│ str       ┆ decimal[3 ┆ i32      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ 8,4]      ┆          ┆ i32       ┆   ┆ str       ┆ decimal[3 ┆ str       ┆ decimal[3 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8,4]      ┆           ┆ 8,4]      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 711500000 ┆ 49000.000 ┆ 1        ┆ 5254214   ┆ … ┆ Thực phẩm ┆ 49000.000 ┆ Snack ăn  ┆ 0.0000    │
│ 0004      ┆ 0         ┆          ┆           ┆   ┆ cho bé    ┆ 0         ┆ dặm       ┆           │
│ 002913000 ┆ 69000.000 ┆ 1        ┆ 7573232   ┆ … ┆ Thực phẩm ┆ 74000.000 ┆ Bột ăn    ┆ 0.0676    │
│ 0030      ┆ 0         ┆          ┆           ┆   ┆ cho bé    ┆ 0         ┆ dặm       ┆           │
│ 349600000 ┆ 75000.000 ┆ 2        ┆ 8187418   ┆ … ┆ Thời      ┆ 75000.000 ┆ Quần áo & ┆ 0.0000    │
│ 0053      ┆ 0         ┆          ┆           ┆   ┆ trang     ┆ 0         ┆ Phụ kiện  ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ sơ sinh   ┆           │
│ 270000000 ┆ 58500.000 ┆ 2        ┆ 8187418   ┆ … ┆ Vệ sinh   ┆ 65000.000 ┆ Khăn khô  ┆ 0.1000    │
│ 0002      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆           ┆           │
│ 002911000 ┆ 89000.000 ┆ 1        ┆ 6931560   ┆ … ┆ Thực phẩm ┆ 99000.000 ┆ Snack ăn  ┆ 0.1010    │
│ 0036      ┆ 0         ┆          ┆           ┆   ┆ cho bé    ┆ 0         ┆ dặm       ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# 1

In [6]:
import polars as pl

first_tx_df = (
    trans
    .group_by("customer_id")
    .agg(pl.col("created_date").min().alias("first_tx_date"))
)

In [8]:
import polars as pl

# mốc thời gian
max_date = trans.select(pl.col("created_date").max()).item()

test_start = max_date.replace(day=1)
test_end   = max_date

train_end   = test_start
train_start = (test_start - pl.duration(days=90))

In [9]:
# user mới tháng test
test_users = (
    first_tx_df
    .filter(
        (pl.col("first_tx_date") >= test_start) &
        (pl.col("first_tx_date") <  test_end)
    )
)

# user mới dùng để học trend
train_users = (
    first_tx_df
    .filter(
        (pl.col("first_tx_date") >= train_start) &
        (pl.col("first_tx_date") <  train_end)
    )
)

In [10]:
print("Train users:", train_users.height)
print("Test users:", test_users.height)

Train users: 397051
Test users: 127105

In [12]:
train_trans_30d = (
    trans
    .join(train_users, on="customer_id", how="inner")
    .filter(
        (pl.col("created_date") >= pl.col("first_tx_date")) &
        (pl.col("created_date") <  pl.col("first_tx_date") + pl.duration(days=30))
    )
)

In [13]:
K_CAT = 3

top_categories = (
    train_trans_30d
    .group_by("category_l1")
    .agg(pl.col("customer_id").n_unique().alias("num_users"))
    .sort("num_users", descending=True)
    .head(K_CAT)
    .select("category_l1")
)

top_categories = top_categories["category_l1"].to_list()
print("Top categories:", top_categories)

Top categories: ['Babycare', 'Sữa', 'Thực phẩm cho bé']

In [15]:
train_first_item = (
    trans
    .join(train_users, on="customer_id", how="inner")
    .filter(pl.col("created_date") == pl.col("first_tx_date"))
    .filter(pl.col("category_l1").is_in(top_categories))
)

In [17]:
K_ITEM = 10

recommended_items = (
    train_first_item
    .group_by("item_id")
    .agg(pl.col("customer_id").n_unique().alias("num_users"))
    .sort("num_users", descending=True)
    .head(K_ITEM)
    .select("item_id")
)

recommended_items = recommended_items["item_id"].to_list()
print("Recommended items:", recommended_items)

Recommended items: ['5950000000001', '0203000000004', '6497000000006', '4950000000002', '6498000000007', '6497000000002', '6488000000001', '0007150000144', '2482000000003', '2541000000002']

In [19]:
test_trans_30d = (
    trans
    .join(test_users, on="customer_id", how="inner")
    .filter(
        (pl.col("created_date") >= pl.col("first_tx_date")) &
        (pl.col("created_date") <  pl.col("first_tx_date") + pl.duration(days=30))
    )
)

In [21]:
user_hit = (
    test_trans_30d
    .with_columns(
        pl.col("item_id").is_in(recommended_items).alias("hit")
    )
    .group_by("customer_id")
    .agg(pl.col("hit").any().alias("user_hit"))
)

In [22]:
hit_rate = user_hit.select(pl.col("user_hit").mean()).item()
print(f"HitRate@{K_ITEM}: {hit_rate:.4f}")

HitRate@10: 0.0755

In [23]:
baseline_items = (
    trans
    .group_by("item_id")
    .count()
    .sort("count", descending=True)
    .head(K_ITEM)
    .select("item_id")["item_id"]
    .to_list()
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_16604\1892206390.py:4: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  .count()

In [24]:
baseline_hit = (
    test_trans_30d
    .with_columns(pl.col("item_id").is_in(baseline_items).alias("hit"))
    .group_by("customer_id")
    .agg(pl.col("hit").any().alias("user_hit"))
    .select(pl.col("user_hit").mean())
    .item()
)

print(f"Baseline HitRate@{K_ITEM}: {baseline_hit:.4f}")

Baseline HitRate@10: 0.0903

In [25]:
# category user mua đầu tiên
test_first_cat = (
    trans
    .join(test_users, on="customer_id", how="inner")
    .filter(pl.col("created_date") == pl.col("first_tx_date"))
    .select("customer_id", "category_l1")
)

cat_hit = (
    test_first_cat
    .with_columns(
        pl.col("category_l1").is_in(top_categories).alias("cat_hit")
    )
    .select(pl.col("cat_hit").mean())
    .item()
)

print(f"Category Hit Rate: {cat_hit:.4f}")

Category Hit Rate: 0.4360

# 2

In [7]:
trans_30d = (
    trans
    .join(first_tx_df, on="customer_id")
    .filter(
        (pl.col("created_date") >= pl.col("first_tx_date")) &
        (pl.col("created_date") <  pl.col("first_tx_date") + pl.duration(days=30))
    )
)

In [10]:
user_by_cat_l1_30d = (
    trans_30d
    .group_by("category_l1")
    .agg(pl.col("customer_id").n_unique().alias("num_users"))
    .sort("num_users", descending=True)
)

In [11]:
total_users = first_tx_df.height

user_by_cat_l1_30d = user_by_cat_l1_30d.with_columns(
    (pl.col("num_users") / total_users).alias("user_ratio")
)

In [13]:
user_by_cat_l1_30d.head(20)

shape: (15, 3)
┌────────────────────────┬───────────┬────────────┐
│ category_l1            ┆ num_users ┆ user_ratio │
│ ---                    ┆ ---       ┆ ---        │
│ str                    ┆ u32       ┆ f64        │
╞════════════════════════╪═══════════╪════════════╡
│ Babycare               ┆ 771967    ┆ 0.300379   │
│ Thực phẩm cho bé       ┆ 744508    ┆ 0.289694   │
│ Sữa                    ┆ 703545    ┆ 0.273755   │
│ Hóa mỹ phẩm cho bé     ┆ 596177    ┆ 0.231977   │
│ Tã                     ┆ 573952    ┆ 0.22333    │
│ …                      ┆ …         ┆ …          │
│ Thực phẩm cho gia đình ┆ 203127    ┆ 0.079038   │
│ Textile                ┆ 190467    ┆ 0.074112   │
│ Phụ kiện               ┆ 138115    ┆ 0.053742   │
│ Hóa mỹ phẩm gia đình   ┆ 99220     ┆ 0.038607   │
│ Gói Hội Viên           ┆ 2         ┆ 7.7822e-7  │
└────────────────────────┴───────────┴────────────┘

In [17]:
user_cat_cnt = (
    trans_30d
    .group_by("customer_id")
    .agg(pl.col("category_l1").n_unique().alias("num_cat_l1"))
)

In [19]:
dominant_cat = (
    trans_30d
    .group_by(["customer_id", "category_l1"])
    .count()
    .sort("count", descending=True)
    .group_by("customer_id")
    .head(1)
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_4368\3025728723.py:4: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  .count()

In [21]:
primary_cat_dist = (
    dominant_cat
    .group_by("category_l1")
    .agg(
        pl.count().alias("num_users")
    )
    .sort("num_users", descending=True)
)
total_users = dominant_cat.height

primary_cat_dist = primary_cat_dist.with_columns(
    (pl.col("num_users") / total_users).alias("user_ratio")
)
print(primary_cat_dist)

shape: (15, 3)
┌────────────────────────┬───────────┬────────────┐
│ category_l1            ┆ num_users ┆ user_ratio │
│ ---                    ┆ ---       ┆ ---        │
│ str                    ┆ u32       ┆ f64        │
╞════════════════════════╪═══════════╪════════════╡
│ Thực phẩm cho bé       ┆ 491475    ┆ 0.191237   │
│ Sữa                    ┆ 424234    ┆ 0.165073   │
│ Babycare               ┆ 369819    ┆ 0.1439     │
│ Tã                     ┆ 255692    ┆ 0.099492   │
│ Hóa mỹ phẩm cho bé     ┆ 232737    ┆ 0.09056    │
│ …                      ┆ …         ┆ …          │
│ Textile                ┆ 57334     ┆ 0.022309   │
│ Thực phẩm cho gia đình ┆ 51557     ┆ 0.020061   │
│ Phụ kiện               ┆ 39629     ┆ 0.01542    │
│ Hóa mỹ phẩm gia đình   ┆ 22993     ┆ 0.008947   │
│ Gói Hội Viên           ┆ 1         ┆ 3.8911e-7  │
└────────────────────────┴───────────┴────────────┘

C:\Users\tncn2\AppData\Local\Temp\ipykernel_4368\1384825304.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_users")

In [23]:
user_total_tx = (
    trans_30d
    .group_by("customer_id")
    .agg(pl.count().alias("total_tx"))
)

dominant_with_ratio = (
    dominant_cat
    .join(user_total_tx, on="customer_id")
    .with_columns(
        (pl.col("count") / pl.col("total_tx")).alias("dominance_ratio")
    )
)
dominance_stats = dominant_with_ratio.select([
    pl.col("dominance_ratio").mean().alias("mean"),
    pl.col("dominance_ratio").median().alias("median"),
    pl.col("dominance_ratio").quantile(0.75).alias("p75"),
])
print(dominance_stats)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_4368\2335309157.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("total_tx"))

shape: (1, 3)
┌──────────┬──────────┬─────┐
│ mean     ┆ median   ┆ p75 │
│ ---      ┆ ---      ┆ --- │
│ f64      ┆ f64      ┆ f64 │
╞══════════╪══════════╪═════╡
│ 0.753421 ┆ 0.909091 ┆ 1.0 │
└──────────┴──────────┴─────┘

In [25]:
food_30d = trans_30d.filter(
    pl.col("category_l1") == "Thực phẩm cho bé"
)

In [27]:
item_user_coverage = (
    food_30d
    .group_by("item_id")
    .agg(
        pl.col("customer_id").n_unique().alias("num_users"),
        pl.count().alias("num_tx"),
        pl.col("price").mean().alias("avg_price")
    )
    .sort("num_users", descending=True)
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_4368\2192275997.py:6: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_tx"),

In [28]:
item_user_coverage = item_user_coverage.with_columns(
    (
        pl.col("num_users").rank(method="dense", descending=True) * 0.6 +
        pl.col("avg_price").rank(method="dense") * 0.4
    ).alias("cold_start_score")
).sort("cold_start_score")

In [29]:
print(item_user_coverage)

shape: (776, 5)
┌───────────────┬───────────┬────────┬───────────────┬──────────────────┐
│ item_id       ┆ num_users ┆ num_tx ┆ avg_price     ┆ cold_start_score │
│ ---           ┆ ---       ┆ ---    ┆ ---           ┆ ---              │
│ str           ┆ u32       ┆ u32    ┆ f64           ┆ f64              │
╞═══════════════╪═══════════╪════════╪═══════════════╪══════════════════╡
│ 2707000000001 ┆ 14181     ┆ 15233  ┆ 2921.555334   ┆ 11.2             │
│ 5358000000001 ┆ 15908     ┆ 17380  ┆ 16744.499374  ┆ 18.6             │
│ 2609000000002 ┆ 12023     ┆ 12754  ┆ 10627.422419  ┆ 20.8             │
│ 2609000000001 ┆ 10658     ┆ 11294  ┆ 10636.165484  ┆ 27.8             │
│ 2808000000001 ┆ 25158     ┆ 27646  ┆ 25488.773737  ┆ 36.4             │
│ …             ┆ …         ┆ …      ┆ …             ┆ …                │
│ 6066000000004 ┆ 8         ┆ 8      ┆ 189687.5      ┆ 704.6            │
│ 5474000000002 ┆ 16        ┆ 18     ┆ 243592.539133 ┆ 704.8            │
│ 5471000000012 ┆ 18        ┆ 18     ┆ 305974.8236   ┆ 708.8            │
│ 5444000000014 ┆ 18        ┆ 18     ┆ 336013.883044 ┆ 710.8            │
│ 5471000000011 ┆ 14        ┆ 14     ┆ 316537.633757 ┆ 712.2            │
└───────────────┴───────────┴────────┴───────────────┴──────────────────┘

In [31]:
first_item = (
    trans
    .join(first_tx_df, on="customer_id")
    .filter(pl.col("created_date") == pl.col("first_tx_date"))
)

starter_food_item = (
    first_item
    .filter(pl.col("category_l1") == "Thực phẩm cho bé")
    .group_by("item_id")
    .agg(pl.col("customer_id").n_unique().alias("num_users"))
    .sort("num_users", descending=True)
)

In [35]:
starter_food_item.head(20)

shape: (20, 2)
┌───────────────┬───────────┐
│ item_id       ┆ num_users │
│ ---           ┆ ---       │
│ str           ┆ u32       │
╞═══════════════╪═══════════╡
│ 2803000000013 ┆ 21091     │
│ 0029130000029 ┆ 18106     │
│ 2803000000011 ┆ 17467     │
│ 2808000000001 ┆ 17109     │
│ 1952000000016 ┆ 14934     │
│ …             ┆ …         │
│ 0029110000054 ┆ 10346     │
│ 7161000000001 ┆ 10004     │
│ 0029110000055 ┆ 9921      │
│ 3880000000001 ┆ 9733      │
│ 2707000000001 ┆ 9654      │
└───────────────┴───────────┘

In [39]:
starter_food_item_named = (
    starter_food_item
    .join(
        item.select(["item_id", "description"]),
        on="item_id",
        how="left"
    )
    .sort("num_users", descending=True)
)
starter_food_item_named.head(15)

shape: (15, 3)
┌───────────────┬───────────┬─────────────────────────────────┐
│ item_id       ┆ num_users ┆ description                     │
│ ---           ┆ ---       ┆ ---                             │
│ str           ┆ u32       ┆ str                             │
╞═══════════════╪═══════════╪═════════════════════════════════╡
│ 2803000000013 ┆ 21091     ┆ ﻿﻿﻿﻿﻿﻿Sữa chua trẻ em vị chuối…       │
│ 0029130000029 ┆ 18106     ┆ ﻿Bột ăn dặm Ridielac Gold 3 Vị…  │
│ 2803000000011 ┆ 17467     ┆ ﻿﻿﻿﻿﻿Sữa chua trẻ em vị dâu tâ…      │
│ 2808000000001 ┆ 17109     ┆ ﻿﻿﻿Sữa chua uống lên men Yakul…    │
│ 1952000000016 ┆ 14934     ┆ ﻿﻿﻿﻿﻿﻿Bột dinh dưỡng HiPP ăn d…       │
│ …             ┆ …         ┆ …                               │
│ 3052000000001 ┆ 11536     ┆ ﻿Dầu Óc Chó Nguyên Chất Thuyền…  │
│ 5358000000001 ┆ 11236     ┆ ﻿﻿Kẹo dẻo Huro 105g Pan Food v…   │
│ 5506000000003 ┆ 10987     ┆ ﻿﻿Bánh gạo Gerber vị Dâu Táo C…   │
│ 6501000000007 ┆ 10795     ┆ Xúc Xích Tiệt Trùng Goldkids C… │
│ 2798000000001 ┆ 10454     ┆ ﻿Phô mai hữu cơ tách muối Seou…  │
└───────────────┴───────────┴─────────────────────────────────┘

# 3

In [6]:
trans_enriched = (
    trans
    .join(
        item.select(["item_id", "category_l1"]),
        on="item_id",
        how="left"
    )
)

In [7]:
# Không được có category_l1 null
null_cat = trans_enriched.filter(pl.col("category_l1").is_null()).height
print("Null category_l1 rows:", null_cat)

Null category_l1 rows: 0

In [12]:
first_tx_df = (
    trans_enriched
    .group_by("customer_id")
    .agg(pl.col("created_date").min().alias("first_tx_date"))
)

In [33]:
from datetime import datetime, timedelta

# Test window bạn muốn
test_start = datetime(2025, 1, 1)
test_end_excl = datetime(2025, 1, 31)  # end-exclusive để cover toàn bộ ngày 30/01

# Train window: 90 ngày trước test_start
train_end = test_start
train_start = train_end - timedelta(days=90)

print("Train:", train_start, "→", train_end)
print("Test :", test_start, "→", test_end_excl)

Train: 2024-10-03 00:00:00 → 2025-01-01 00:00:00
Test : 2025-01-01 00:00:00 → 2025-01-31 00:00:00

In [34]:
train_users = first_tx_df.filter(
    (pl.col("first_tx_date") >= train_start) &
    (pl.col("first_tx_date") <  train_end)
)

test_users = first_tx_df.filter(
    (pl.col("first_tx_date") >= test_start) &
    (pl.col("first_tx_date") <  test_end_excl)
)

print("Train users:", train_users.height)
print("Test users :", test_users.height)

Train users: 397051
Test users : 127672

In [36]:
train_trans_30d = (
    trans_enriched
    .join(train_users, on="customer_id", how="inner")
    .filter(
        (pl.col("created_date") >= pl.col("first_tx_date")) &
        (pl.col("created_date") <  pl.col("first_tx_date") + pl.duration(days=30))
    )
)

In [37]:
K_CAT = 5

top_categories_df = (
    train_trans_30d
    .group_by("category_l1")
    .agg(pl.col("customer_id").n_unique().alias("num_users"))
    .sort("num_users", descending=True)
    .head(K_CAT)
)

top_categories = top_categories_df["category_l1"].to_list()
print("Top categories:", top_categories)

Top categories: ['Babycare', 'Sữa', 'Thực phẩm cho bé', 'Hóa mỹ phẩm cho bé', 'Tã']

In [38]:
train_first_item = (
    trans_enriched
    .join(train_users, on="customer_id", how="inner")
    .filter(pl.col("created_date") == pl.col("first_tx_date"))
    .filter(pl.col("category_l1").is_in(top_categories))
)

In [40]:
K_HIT = 10        # Hit@10
K_CAT = 3         # vẫn giữ 3 category
HYBRID_ALPHA = 0.6

# Tổng = 10
# Cat #1: 5 item
# Cat #2: 3 item
# Cat #3: 2 item
alloc = [5, 3, 2]

cat_to_items = {}

for cat, n_take in zip(top_categories, alloc):
    items_cat = (
        train_first_item
        .filter(pl.col("category_l1") == cat)
        .group_by("item_id")
        .agg(pl.col("customer_id").n_unique().alias("num_users"))
        .sort("num_users", descending=True)
        .head(n_take)
        .select("item_id")
    )["item_id"].to_list()

    cat_to_items[cat] = items_cat

In [41]:
rec_items_trend = []
seen = set()

for cat in top_categories:
    for it in cat_to_items.get(cat, []):
        if it not in seen:
            rec_items_trend.append(it)
            seen.add(it)

# đảm bảo đúng Hit@10
rec_items_trend = rec_items_trend[:K_HIT]

print("Trend items (Hit@10):", rec_items_trend)

Trend items (Hit@10): ['5950000000001', '0203000000004', '6497000000006', '6498000000007', '6497000000002', '4950000000002', '6488000000001', '2482000000003', '2808000000001', '1952000000016']

In [42]:
baseline_items = (
    trans_enriched
    .filter((pl.col("created_date") >= train_start) &
            (pl.col("created_date") <  train_end))
    .group_by("item_id")
    .count()
    .sort("count", descending=True)
    .head(K_HIT)
    .select("item_id")
)["item_id"].to_list()

print("Baseline items (Hit@10):", baseline_items)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_16604\17466415.py:6: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  .count()

Baseline items (Hit@10): ['4690000000001', '1512000000004', '2803000000013', '7176000000002', '6768000000005', '3773000000004', '2803000000011', '5950000000001', '0020010000438', '2798000000001']

In [43]:
n_trend = int(round(K_HIT * HYBRID_ALPHA))   # 6
n_base  = K_HIT - n_trend                    # 4

hybrid_items = []
seen = set()

for it in rec_items_trend[:n_trend] + baseline_items:
    if it not in seen:
        hybrid_items.append(it)
        seen.add(it)
    if len(hybrid_items) == K_HIT:
        break

print("Hybrid items (Hit@10):", hybrid_items)

Hybrid items (Hit@10): ['5950000000001', '0203000000004', '6497000000006', '6498000000007', '6497000000002', '4950000000002', '4690000000001', '1512000000004', '2803000000013', '7176000000002']

In [45]:
def hitrate_at_k(test_df, rec_items):
    user_hit = (
        test_df
        .with_columns(pl.col("item_id").is_in(rec_items).alias("hit"))
        .group_by("customer_id")
        .agg(pl.col("hit").any().alias("user_hit"))
    )
    return user_hit.select(pl.col("user_hit").mean()).item()

print("Trend Hit@10   :", hitrate_at_k(test_trans_30d, rec_items_trend))
print("Baseline Hit@10:", hitrate_at_k(test_trans_30d, baseline_items))
print("Hybrid Hit@10  :", hitrate_at_k(test_trans_30d, hybrid_items))

Trend Hit@10   : 0.0769599937059911
Baseline Hit@10: 0.09254553322056568
Hybrid Hit@10  : 0.10341843357853743

In [46]:
print("Category Hit Rate:", cat_hit)

Category Hit Rate: 0.4359827585117208

# số lượng coldstart user

In [28]:
import pickle
import polars as pl
import numpy as np

with open("final_groundtruth.pkl", "rb") as f:
    ground_dict = pickle.load(f)

print("Num users in ground_dict:", len(ground_dict))
print("Sample keys:", list(ground_dict.keys())[:5])

C:\Users\tncn2\AppData\Local\Temp\ipykernel_9068\525071296.py:6: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  ground_dict = pickle.load(f)

Num users in ground_dict: 644970
Sample keys: ['customer_id', 'item_id']

In [33]:
import polars as pl

# 1. Build DataFrame thô (giữ item_id là List[String])
ground_df_raw = pl.DataFrame({
    "customer_id": pl.Series(ground_dict["customer_id"]).cast(pl.Utf8),
    "item_id": pl.Series(ground_dict["item_id"])   # List[String]
})

print("Before explode:", ground_df_raw.shape)

# 2. Explode item list → 1 item / dòng
ground_df_raw = ground_df_raw.explode("item_id")

# 3. Cast item_id từ string → int
ground_df_raw = ground_df_raw.with_columns(
    pl.col("item_id").cast(pl.Int64)
)

print("After explode:", ground_df_raw.shape)
print("Unique users:", ground_df_raw.select("customer_id").unique().height)

Before explode: (644970, 2)
After explode: (2665926, 2)
Unique users: 644970

In [38]:
import polars as pl
from datetime import datetime

trans = trans.with_columns(pl.col("customer_id").cast(pl.Utf8))
ground_df_raw = ground_df_raw.with_columns(pl.col("customer_id").cast(pl.Utf8))

In [39]:
gt_users_feb = (
    ground_df_raw
    .select("customer_id")
    .unique()
)

print("Groundtruth users (Feb):", gt_users_feb.height)

Groundtruth users (Feb): 644970

In [40]:
feb_start = datetime(2025, 2, 1)

past_users = (
    trans
    .filter(pl.col("created_date") < feb_start)
    .select("customer_id")
    .unique()
)

print("Users with history before Feb:", past_users.height)

Users with history before Feb: 2569978

In [41]:
cold_users_feb = gt_users_feb.join(
    past_users,
    on="customer_id",
    how="anti"
)

print("Cold-start users (Feb):", cold_users_feb.height)
print("Cold-start ratio:",
      f"{(cold_users_feb.height / gt_users_feb.height):.2%}" if gt_users_feb.height > 0 else "NA")

Cold-start users (Feb): 135235
Cold-start ratio: 20.97%

# t2 024 t2 2025

In [25]:
import polars as pl

TOP_K = 100

trans_202402 = trans.filter(
    (pl.col("created_date") >= pl.datetime(2024, 2, 1)) &
    (pl.col("created_date") <  pl.datetime(2024, 3, 1))
)

popular_item_list = (
    trans_202402
    .group_by("item_id")
    .agg(pl.count().alias("cnt"))
    .sort("cnt", descending=True)
    .head(TOP_K)
    .get_column("item_id")
    .to_list()
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\3736337841.py:13: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("cnt"))

In [7]:
print("train tx 02/2024:", trans_202402.height)
print("popular items:", len(popular_item_list))

train tx 02/2024: 3079387
popular items: 100

In [9]:
import pickle
import pandas as pd
import polars as pl

pkl_path = "final_groundtruth.pkl"

with open(pkl_path, "rb") as f:
    gt_obj = pickle.load(f)

# Case A: dict customer_id -> list[item_id]
if isinstance(gt_obj, dict):
    gt_pl = pl.DataFrame({
        "customer_id": list(gt_obj.keys()),
        "gt_items": list(gt_obj.values())
    })

# Case B/C: pandas DataFrame
elif isinstance(gt_obj, pd.DataFrame):
    gt_pl = pl.from_pandas(gt_obj)

# Case B/C: polars DataFrame
elif isinstance(gt_obj, pl.DataFrame):
    gt_pl = gt_obj

else:
    raise TypeError(f"Unsupported pkl type: {type(gt_obj)}")

# Chuẩn hóa về đúng schema: customer_id, gt_items(list)
if "gt_items" not in gt_pl.columns:
    if {"customer_id", "item_id"}.issubset(set(gt_pl.columns)):
        gt_pl = gt_pl.rename({
            "item_id": "gt_items"
            })
    else:
        raise ValueError(f"Ground truth must contain gt_items or (customer_id, item_id). Columns={gt_pl.columns}")

# Ép kiểu list + dọn null để tránh mean(None)
gt_pl = gt_pl.with_columns(
    pl.col("gt_items").cast(pl.List(pl.Utf8), strict=False).fill_null(pl.lit([]))
)

print("GT users:", gt_pl.height)
print("GT empty-list users:", gt_pl.filter(pl.col("gt_items").list.len() == 0).height)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\3209515207.py:8: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  gt_obj = pickle.load(f)

GT users: 644970
GT empty-list users: 0

In [10]:
pred_202502 = gt_pl.with_columns(
    pl.lit(popular_item_list).alias("pred_items")
)

eval_df = pred_202502.with_columns(
    pl.col("pred_items")
      .list.set_intersection(pl.col("gt_items"))
      .list.len()
      .gt(0)
      .alias("hit")
)

hit_rate = eval_df.select(pl.col("hit").mean()).item()
print(f"HitRate@{TOP_K}:", hit_rate)

HitRate@100: 0.4701955129695955

# popular item 3 tháng gần nhất

In [24]:
import polars as pl

TOP_K = 100

trans_train = trans.filter(
    (pl.col("created_date") >= pl.datetime(2024, 11, 1)) &
    (pl.col("created_date") <  pl.datetime(2025, 2, 1))
)

popular_item_list_3m = (
    trans_train
    .group_by("item_id")
    .agg(pl.count().alias("cnt"))
    .sort("cnt", descending=True)
    .head(TOP_K)
    .get_column("item_id")
    .to_list()
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\1179561785.py:13: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("cnt"))

In [14]:
import pickle
import pandas as pd
import polars as pl

pkl_path = "final_groundtruth.pkl"

with open(pkl_path, "rb") as f:
    gt_obj = pickle.load(f)

# Case A: dict customer_id -> list[item_id]
if isinstance(gt_obj, dict):
    gt_pl = pl.DataFrame({
        "customer_id": list(gt_obj.keys()),
        "gt_items": list(gt_obj.values())
    })

# Case B/C: pandas DataFrame
elif isinstance(gt_obj, pd.DataFrame):
    gt_pl = pl.from_pandas(gt_obj)

# Case B/C: polars DataFrame
elif isinstance(gt_obj, pl.DataFrame):
    gt_pl = gt_obj

else:
    raise TypeError(f"Unsupported pkl type: {type(gt_obj)}")

# Chuẩn hóa về đúng schema: customer_id, gt_items(list)
if "gt_items" not in gt_pl.columns:
    if {"customer_id", "item_id"}.issubset(set(gt_pl.columns)):
        gt_pl = gt_pl.rename({
            "item_id": "gt_items"
            })
    else:
        raise ValueError(f"Ground truth must contain gt_items or (customer_id, item_id). Columns={gt_pl.columns}")

# Ép kiểu list + dọn null để tránh mean(None)
gt_pl = gt_pl.with_columns(
    pl.col("gt_items").cast(pl.List(pl.Utf8), strict=False).fill_null(pl.lit([]))
)

print("GT users:", gt_pl.height)
print("GT empty-list users:", gt_pl.filter(pl.col("gt_items").list.len() == 0).height)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\3209515207.py:8: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  gt_obj = pickle.load(f)

GT users: 644970
GT empty-list users: 0

In [22]:
pred_202502 = gt_pl.with_columns(
    pl.lit(popular_item_list_3m).alias("pred_items")
)

eval_df = pred_202502.with_columns(
    pl.col("pred_items")
      .list.set_intersection(pl.col("gt_items"))
      .list.len()
      .gt(0)
      .alias("hit")
)

hit_rate = eval_df.select(pl.col("hit").mean()).item()
print(f"HitRate@{TOP_K}:", hit_rate)

HitRate@100: 0.538852969905577

In [26]:
K = 10

list_202402 = popular_item_list[:K]
list_3m     = popular_item_list_3m[:K]

def hitrate(gt_pl, rec_list):
    return (
        gt_pl.with_columns(pl.lit(rec_list).alias("pred_items"))
             .with_columns(
                 pl.col("pred_items")
                   .list.set_intersection(pl.col("gt_items"))
                   .list.len()
                   .gt(0)
                   .alias("hit")
             )
             .select(pl.col("hit").mean())
             .item()
    )

print("HitRate@10 - 02/2024 :", hitrate(gt_pl, list_202402))
print("HitRate@10 - 3 months:", hitrate(gt_pl, list_3m))

HitRate@10 - 02/2024 : 0.1328247825480255
HitRate@10 - 3 months: 0.19689287873854597

# cold start item

In [32]:
import polars as pl

START_DATE = pl.datetime(2024, 8, 1)
END_DATE   = pl.datetime(2025, 2, 1)   # hết T1/2025

trans_win = trans.filter(
    (pl.col("created_date") >= START_DATE) &
    (pl.col("created_date") <  END_DATE)
)

In [33]:
user_first_tx = (
    trans
    .group_by("customer_id")
    .agg(pl.col("created_date").min().alias("first_tx_date"))
)

In [34]:
cold_users = (
    user_first_tx
    .filter(
        (pl.col("first_tx_date") >= START_DATE) &
        (pl.col("first_tx_date") <  END_DATE)
    )
)

In [35]:
cold_tx_30d = (
    trans
    .join(cold_users, on="customer_id", how="inner")
    .filter(
        (pl.col("created_date") >= pl.col("first_tx_date")) &
        (pl.col("created_date") <  pl.col("first_tx_date") + pl.duration(days=30))
    )
)

In [36]:
top100_cold_items = (
    cold_tx_30d
    .group_by("item_id")
    .agg(pl.count().alias("purchase_cnt"))
    .sort("purchase_cnt", descending=True)
    .head(100)
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\4260263109.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("purchase_cnt"))

In [40]:
K = 10

top10_items = (
    top100_cold_items
    .head(K)
    .get_column("item_id")
    .to_list()
)

In [42]:
import pickle
import pandas as pd
import polars as pl

pkl_path = "final_groundtruth.pkl"

with open(pkl_path, "rb") as f:
    gt_obj = pickle.load(f)

# Case A: dict customer_id -> list[item_id]
if isinstance(gt_obj, dict):
    gt_pl = pl.DataFrame({
        "customer_id": list(gt_obj.keys()),
        "gt_items": list(gt_obj.values())
    })

# Case B/C: pandas DataFrame
elif isinstance(gt_obj, pd.DataFrame):
    gt_pl = pl.from_pandas(gt_obj)

# Case B/C: polars DataFrame
elif isinstance(gt_obj, pl.DataFrame):
    gt_pl = gt_obj

else:
    raise TypeError(f"Unsupported pkl type: {type(gt_obj)}")

# Chuẩn hóa về đúng schema: customer_id, gt_items(list)
if "gt_items" not in gt_pl.columns:
    if {"customer_id", "item_id"}.issubset(set(gt_pl.columns)):
        gt_pl = gt_pl.rename({
            "item_id": "gt_items"
            })
    else:
        raise ValueError(f"Ground truth must contain gt_items or (customer_id, item_id). Columns={gt_pl.columns}")

# Ép kiểu list + dọn null để tránh mean(None)
gt_pl = gt_pl.with_columns(
    pl.col("gt_items").cast(pl.List(pl.Utf8), strict=False).fill_null(pl.lit([]))
)

print("GT users:", gt_pl.height)
print("GT empty-list users:", gt_pl.filter(pl.col("gt_items").list.len() == 0).height)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\2477230397.py:8: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  gt_obj = pickle.load(f)

GT users: 644970
GT empty-list users: 0

In [43]:
cold_users_202502 = (
    gt_pl
    .join(
        cold_users.select("customer_id"),
        on="customer_id",
        how="inner"
    )
)

In [44]:
precision_df = cold_users_202502.with_columns(
    (
        pl.col("gt_items")
          .list.set_intersection(pl.lit(top10_items))
          .list.len()
          / K
    ).alias("precision_at_10")
)

In [45]:
precision_df = cold_users_202502.with_columns(
    (
        pl.col("gt_items")
          .list.set_intersection(pl.lit(top10_items))
          .list.len()
          / K
    ).alias("precision_at_10")
)

In [46]:
precision_at_10 = precision_df.select(
    pl.col("precision_at_10").mean()
).item()

print("Precision@10 (cold-start users, Feb-2025):", precision_at_10)

Precision@10 (cold-start users, Feb-2025): 0.0219264902100723

In [48]:
precision_df.select(
    pl.col("precision_at_10").min().alias("min_precision"),
    pl.col("precision_at_10").mean().alias("mean_precision"),
    pl.col("precision_at_10").max().alias("max_precision"),
)

shape: (1, 3)
┌───────────────┬────────────────┬───────────────┐
│ min_precision ┆ mean_precision ┆ max_precision │
│ ---           ┆ ---            ┆ ---           │
│ f64           ┆ f64            ┆ f64           │
╞═══════════════╪════════════════╪═══════════════╡
│ 0.0           ┆ 0.021926       ┆ 0.7           │
└───────────────┴────────────────┴───────────────┘

# window

In [49]:
import polars as pl

trans_m = trans.with_columns(
    pl.col("created_date").dt.truncate("1mo").alias("month")
)

In [52]:
trans_m = trans.with_columns(
    pl.col("created_date").dt.truncate("1mo").alias("month")
)

In [53]:
from datetime import datetime

def add_months(dt: datetime, n: int) -> datetime:
    y = dt.year + (dt.month - 1 + n) // 12
    m = (dt.month - 1 + n) % 12 + 1
    return datetime(y, m, 1)

In [56]:
from datetime import datetime

def get_cold_users_in_month(trans_m: pl.DataFrame, target_month: datetime):

    prev_start = add_months(target_month, -3)
    prev_end   = target_month   # không include target month

    users_t = (
        trans_m
        .filter(pl.col("month") == target_month)
        .select("customer_id")
        .unique()
    )

    users_prev = (
        trans_m
        .filter(
            (pl.col("month") >= prev_start) &
            (pl.col("month") <  prev_end)
        )
        .select("customer_id")
        .unique()
    )

    cold_users = users_t.join(
        users_prev,
        on="customer_id",
        how="anti"
    )

    return cold_users

In [58]:
from datetime import datetime

start_month = datetime(2024, 4, 1)
end_month   = datetime(2025, 1, 1)

In [60]:
cur = start_month
all_cold_items = []   # <-- PHẢI CÓ DÒNG NÀY
while cur <= end_month:

    print(f"Processing month {cur:%Y-%m}")

    cold_users = get_cold_users_in_month(trans_m, cur)

    if cold_users.height > 0:
        cold_tx = (
            trans_m
            .filter(pl.col("month") == cur)
            .join(cold_users, on="customer_id", how="inner")
        )
        all_cold_items.append(
            cold_tx
            .select("item_id")
        )

    cur = add_months(cur, 1)

Processing month 2024-04
Processing month 2024-05
Processing month 2024-06
Processing month 2024-07
Processing month 2024-08
Processing month 2024-09
Processing month 2024-10
Processing month 2024-11
Processing month 2024-12
Processing month 2025-01

In [61]:
assert len(all_cold_items) > 0, "No cold-start items collected"

cold_item_union = (
    pl.concat(all_cold_items)
      .unique(subset=["item_id"])
)

In [62]:
cold_item_union.shape

(16918, 1)

In [63]:
import polars as pl

assert len(all_cold_items) > 0, "all_cold_items is empty"

cold_items_all = pl.concat(all_cold_items)

In [64]:
print("Total cold-start transactions:", cold_items_all.height)
print("Unique cold-start items:", cold_items_all.select(pl.col("item_id").n_unique()).item())

Total cold-start transactions: 5833481
Unique cold-start items: 16918

In [65]:
top100_cold_items = (
    cold_items_all
    .group_by("item_id")
    .agg(pl.count().alias("purchase_cnt"))
    .sort("purchase_cnt", descending=True)
    .head(100)
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\68708513.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("purchase_cnt"))

In [67]:
top100_item_list = top100_cold_items["item_id"].to_list()

In [68]:
top10_item_list = top100_item_list[:10]

In [69]:
import pickle
import pandas as pd
import polars as pl

pkl_path = "final_groundtruth.pkl"

with open(pkl_path, "rb") as f:
    gt_obj = pickle.load(f)

# Case A: dict customer_id -> list[item_id]
if isinstance(gt_obj, dict):
    gt_pl = pl.DataFrame({
        "customer_id": list(gt_obj.keys()),
        "gt_items": list(gt_obj.values())
    })

# Case B/C: pandas DataFrame
elif isinstance(gt_obj, pd.DataFrame):
    gt_pl = pl.from_pandas(gt_obj)

# Case B/C: polars DataFrame
elif isinstance(gt_obj, pl.DataFrame):
    gt_pl = gt_obj

else:
    raise TypeError(f"Unsupported pkl type: {type(gt_obj)}")

# Chuẩn hóa về đúng schema: customer_id, gt_items(list)
if "gt_items" not in gt_pl.columns:
    if {"customer_id", "item_id"}.issubset(set(gt_pl.columns)):
        gt_pl = gt_pl.rename({
            "item_id": "gt_items"
            })
    else:
        raise ValueError(f"Ground truth must contain gt_items or (customer_id, item_id). Columns={gt_pl.columns}")

# Ép kiểu list + dọn null để tránh mean(None)
gt_pl = gt_pl.with_columns(
    pl.col("gt_items").cast(pl.List(pl.Utf8), strict=False).fill_null(pl.lit([]))
)

print("GT users:", gt_pl.height)
print("GT empty-list users:", gt_pl.filter(pl.col("gt_items").list.len() == 0).height)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_2056\2477230397.py:8: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  gt_obj = pickle.load(f)

GT users: 644970
GT empty-list users: 0

In [70]:
K = 10

top10_items = (
    top100_cold_items
    .head(K)
    .get_column("item_id")
    .to_list()
)

print("Top10 cold-start items:", top10_items)

Top10 cold-start items: ['4690000000001', '6766000000002', '1215000000002', '1512000000004', '5950000000001', '0020010000210', '0203000000004', '0175000000007', '0020020000185', '4603024000001']

In [71]:
from datetime import datetime

target_month = datetime(2025, 2, 1)

# users có giao dịch trong 02/2025 (lấy từ ground truth)
users_t = gt_pl.select("customer_id").unique()

# users có giao dịch trong 3 tháng trước (11,12/2024 + 01/2025)
prev_start = add_months(target_month, -3)   # 2024-11-01
prev_end   = target_month                   # < 2025-02-01

users_prev = (
    trans_m
    .filter(
        (pl.col("month") >= prev_start) &
        (pl.col("month") <  prev_end)
    )
    .select("customer_id")
    .unique()
)

# cold-start users tại 02/2025
cold_users_202502 = users_t.join(
    users_prev,
    on="customer_id",
    how="anti"
)

print("Cold-start users in Feb-2025:", cold_users_202502.height)

Cold-start users in Feb-2025: 208226

In [72]:
cold_gt_202502 = (
    gt_pl
    .join(
        cold_users_202502,
        on="customer_id",
        how="inner"
    )
)

print("Cold-start users with GT:", cold_gt_202502.height)

Cold-start users with GT: 208226

In [73]:
K = 10

top10_items = (
    top100_cold_items
    .head(K)
    .get_column("item_id")
    .to_list()
)

In [74]:
precision_df = cold_gt_202502.with_columns(
    (
        pl.col("gt_items")
          .list.set_intersection(pl.lit(top10_items))
          .list.len()
          / K
    ).alias("precision_at_10")
)

precision_at_10 = precision_df.select(
    pl.col("precision_at_10").mean()
).item()

print("Precision@10 (cold-start, Feb-2025):", precision_at_10)

Precision@10 (cold-start, Feb-2025): 0.016917675986668334

import polars as pl

trans_m = trans.with_columns(
    pl.col("created_date").dt.truncate("1mo").alias("month")
)

# eda

# popular tháng 1

In [ ]:
trans_jan = trans.filter(
    (pl.col("created_date") >= pl.datetime(2025, 1, 1)) &
    (pl.col("created_date") < pl.datetime(2025, 2, 1))
)

In [59]:
popular_item_jan = (
    trans_jan
    .group_by("item_id")
    .agg(
        pl.count().alias("n_tx"),
        pl.sum("quantity").alias("total_qty")
    )
    .sort("n_tx", descending=True)
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_22976\1127971888.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("n_tx"),

In [60]:
popular_item_jan = popular_item_jan.join(
    item.select("item_id", "category_l1", "category", "description"),
    on="item_id",
    how="left"
)

In [61]:
popular_cat_l1_jan = (
    popular_item_jan
    .group_by("category_l1")
    .agg(
        pl.sum("n_tx").alias("total_tx"),
        pl.sum("total_qty").alias("total_qty"),
        pl.count().alias("n_items")
    )
    .sort("total_tx", descending=True)
)

popular_cat_l1_jan

C:\Users\tncn2\AppData\Local\Temp\ipykernel_22976\1682066852.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("n_items")

shape: (15, 4)
┌──────────────────────┬──────────┬───────────┬─────────┐
│ category_l1          ┆ total_tx ┆ total_qty ┆ n_items │
│ ---                  ┆ ---      ┆ ---       ┆ ---     │
│ str                  ┆ u32      ┆ i32       ┆ u32     │
╞══════════════════════╪══════════╪═══════════╪═════════╡
│ Thực phẩm cho bé     ┆ 1119518  ┆ 1326241   ┆ 614     │
│ Sữa                  ┆ 382947   ┆ 517035    ┆ 272     │
│ Babycare             ┆ 302289   ┆ 334361    ┆ 1169    │
│ Tã                   ┆ 277929   ┆ 407235    ┆ 237     │
│ Hóa mỹ phẩm cho bé   ┆ 270803   ┆ 290505    ┆ 255     │
│ …                    ┆ …        ┆ …         ┆ …       │
│ Phụ kiện             ┆ 66673    ┆ 67276     ┆ 1443    │
│ Textile              ┆ 55424    ┆ 65909     ┆ 355     │
│ Đồ chơi & Sách       ┆ 52619    ┆ 53516     ┆ 1341    │
│ Hóa mỹ phẩm gia đình ┆ 14005    ┆ 15081     ┆ 237     │
│ Gói Hội Viên         ┆ 114      ┆ 114       ┆ 3       │
└──────────────────────┴──────────┴───────────┴─────────┘

In [7]:
trans_jan = trans.filter(
    (pl.col("created_date") >= pl.datetime(2024, 2, 1)) &
    (pl.col("created_date") <  pl.datetime(2024, 3, 1))
)
popular_item_jan = (
    trans_jan
    .group_by("item_id")
    .agg(
        pl.count().alias("n_tx"),
        pl.sum("quantity").alias("total_qty")
    )
    .sort("n_tx", descending=True)
)
popular_item_jan = popular_item_jan.join(
    item.select("item_id", "category_l1", "category", "description"),
    on="item_id",
    how="left"
)
popular_cat_l1_jan = (
    popular_item_jan
    .group_by("category_l1")
    .agg(
        pl.sum("n_tx").alias("total_tx"),
        pl.sum("total_qty").alias("total_qty"),
        pl.count().alias("n_items")
    )
    .sort("total_tx", descending=True)
)

popular_cat_l1_jan

C:\Users\tncn2\AppData\Local\Temp\ipykernel_22244\1099531642.py:9: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("n_tx"),
C:\Users\tncn2\AppData\Local\Temp\ipykernel_22244\1099531642.py:25: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("n_items")

shape: (14, 4)
┌────────────────────────┬──────────┬───────────┬─────────┐
│ category_l1            ┆ total_tx ┆ total_qty ┆ n_items │
│ ---                    ┆ ---      ┆ ---       ┆ ---     │
│ str                    ┆ u32      ┆ i32       ┆ u32     │
╞════════════════════════╪══════════╪═══════════╪═════════╡
│ Thực phẩm cho bé       ┆ 952088   ┆ 1123519   ┆ 654     │
│ Babycare               ┆ 348161   ┆ 384141    ┆ 1306    │
│ Sữa                    ┆ 343061   ┆ 457112    ┆ 297     │
│ Tã                     ┆ 267915   ┆ 358123    ┆ 276     │
│ Hóa mỹ phẩm cho bé     ┆ 258278   ┆ 273364    ┆ 266     │
│ …                      ┆ …        ┆ …         ┆ …       │
│ Thực phẩm cho gia đình ┆ 88878    ┆ 109982    ┆ 278     │
│ Đồ chơi & Sách         ┆ 83593    ┆ 84731     ┆ 1626    │
│ Textile                ┆ 62601    ┆ 73306     ┆ 356     │
│ Phụ kiện               ┆ 52529    ┆ 53007     ┆ 1567    │
│ Hóa mỹ phẩm gia đình   ┆ 45467    ┆ 47294     ┆ 316     │
└────────────────────────┴──────────┴───────────┴─────────┘