# Load Data

In [1]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
def read_parquet_transaction(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    purchase_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    purchase_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_chunk_files]) if purchase_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return purchase_chunk_df

In [3]:
def read_parquet_item(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    item_chunk_files = [file for file in files if 'item_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return item_chunk_df

In [4]:
item = read_parquet_item('dataset')
item.head()

shape: (5, 34)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ volume    ┆ material  ┆ sale_stat ┆ descripti │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ ---       ┆ ---       ┆ us        ┆ on_new    │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆           ┆           ┆ i32       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 004        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không xác │
│       ┆ 150        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ định      │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 015        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 094        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 098        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
trans = read_parquet_transaction("./dataset")
trans.head()

shape: (5, 16)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ timestamp  ┆ user_id   ┆ item_id   ┆ event_typ ┆ … ┆ payment  ┆ location ┆ discount  ┆ is_delete │
│ ---        ┆ ---       ┆ ---       ┆ e         ┆   ┆ ---      ┆ ---      ┆ ---       ┆ d         │
│ i64        ┆ str       ┆ str       ┆ ---       ┆   ┆ str      ┆ i32      ┆ decimal[3 ┆ ---       │
│            ┆           ┆           ┆ str       ┆   ┆          ┆          ┆ 8,4]      ┆ bool      │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 1735064221 ┆ ca12702dd ┆ 711500000 ┆ Purchase  ┆ … ┆ VietQR   ┆ 656      ┆ 0.0000    ┆ false     │
│            ┆ f55acaa9f ┆ 0004      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ b767e10fa ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ aa6…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735068481 ┆ 54314ce86 ┆ 002913000 ┆ Purchase  ┆ … ┆ Tiền mặt ┆ 143      ┆ 0.0000    ┆ false     │
│            ┆ 269f4849f ┆ 0030      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 9a4c3fc85 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ d94…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735069843 ┆ 4799de402 ┆ 349600000 ┆ Purchase  ┆ … ┆ MoMo     ┆ 213      ┆ 0.0000    ┆ false     │
│            ┆ 2b58689b2 ┆ 0053      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ b9fb37122 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 479…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735069779 ┆ 4799de402 ┆ 270000000 ┆ Purchase  ┆ … ┆ MoMo     ┆ 213      ┆ 13000.000 ┆ false     │
│            ┆ 2b58689b2 ┆ 0002      ┆           ┆   ┆          ┆          ┆ 0         ┆           │
│            ┆ b9fb37122 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 479…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735379373 ┆ 3b2423f73 ┆ 002911000 ┆ Purchase  ┆ … ┆ MoMo     ┆ 590      ┆ 10000.000 ┆ false     │
│            ┆ 0815273df ┆ 0036      ┆           ┆   ┆          ┆          ┆ 0         ┆           │
│            ┆ d6f6220b0 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ c5c…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [6]:
def read_parquet_user(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    user_chunk_files = [file for file in files if 'user_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    user_chunk_df = pl.concat([pl.read_parquet(file) for file in user_chunk_files]) if user_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return user_chunk_df

In [8]:
user = read_parquet_user("./dataset")
user.head()

shape: (5, 18)
┌────────────┬────────┬──────────┬────────────┬───┬────────────┬──────────┬────────────┬───────────┐
│ customer_i ┆ gender ┆ location ┆ province   ┆ … ┆ install_da ┆ district ┆ user_id    ┆ is_delete │
│ d          ┆ ---    ┆ ---      ┆ ---        ┆   ┆ te         ┆ ---      ┆ ---        ┆ d         │
│ ---        ┆ str    ┆ i32      ┆ str        ┆   ┆ ---        ┆ str      ┆ str        ┆ ---       │
│ i32        ┆        ┆          ┆            ┆   ┆ i64        ┆          ┆            ┆ bool      │
╞════════════╪════════╪══════════╪════════════╪═══╪════════════╪══════════╪════════════╪═══════════╡
│ 14732      ┆ Nam    ┆ 155      ┆ Hồ Chí     ┆ … ┆ 1306281600 ┆ 7        ┆ e1e4820665 ┆ false     │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆          ┆ 2bf8c279ff ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ 0206c69a80 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ …          ┆           │
│ 15126      ┆ Nữ     ┆ 300      ┆ Hồ Chí     ┆ … ┆ 1306281600 ┆ Thủ Đức  ┆ 7789175920 ┆ false     │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆          ┆ 4bd27e69fb ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ 11a7b92889 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ …          ┆           │
│ 29718      ┆ Nữ     ┆ 157      ┆ Bến Tre    ┆ … ┆ 1582070400 ┆ Bến Tre  ┆ b8041b584a ┆ false     │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ 0bb6655361 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ 727a0a6108 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ …          ┆           │
│ 30077      ┆ Nữ     ┆ 53       ┆ Hồ Chí     ┆ … ┆ 1314230400 ┆ 1        ┆ c52ceaca44 ┆ false     │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆          ┆ a83ec41a21 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ 9cfaff0e05 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ …          ┆           │
│ 30085      ┆ Nữ     ┆ 660      ┆ Hồ Chí     ┆ … ┆ 1314230400 ┆ Tân Phú  ┆ 74ac5764f5 ┆ false     │
│            ┆        ┆          ┆ Minh       ┆   ┆            ┆          ┆ d67d341aac ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ f238d7762f ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆          ┆ …          ┆           │
└────────────┴────────┴──────────┴────────────┴───┴────────────┴──────────┴────────────┴───────────┘

# 2.

In [10]:
import polars as pl
from datetime import datetime

begin_hist   = datetime(2024, 1, 1)
end_hist     = datetime(2024, 10, 31)
begin_recent = datetime(2024, 11, 1)
end_recent   = datetime(2024, 11, 30)

hist = (
    trans.filter(
        (pl.col("created_date") >= begin_hist) &
        (pl.col("created_date") <= end_hist)
    )
    .select(["customer_id", "item_id"])
)

recent = (
    trans.filter(
        (pl.col("created_date") >= begin_recent) &
        (pl.col("created_date") <= end_recent)
    )
    .select(["customer_id", "item_id"])
)