# Download các thư viện cần thiết

In [1]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Tạo hàm để đọc file parquet (đọc các file parquet - data sau khi được processed)

In [3]:
def read_parquet_user(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    user_chunk_files = [file for file in files if 'user_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    user_chunk_df = pl.concat([pl.read_parquet(file) for file in user_chunk_files]) if user_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return user_chunk_df

In [4]:
def read_parquet_item(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    item_chunk_files = [file for file in files if 'item_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return item_chunk_df

In [5]:
def read_parquet_transaction(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    purchase_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    purchase_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_chunk_files]) if purchase_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return purchase_chunk_df

# Tạo hàm lưu file parquet sau mỗi task

In [6]:
brand_segment_df = pl.read_parquet("./new-feature/brand_segment.parquet")
brand_segment_df.head()

shape: (5, 2)
┌─────────────┬───────────────┐
│ category_l1 ┆ brand_segment │
│ ---         ┆ ---           │
│ str         ┆ i64           │
╞═════════════╪═══════════════╡
│ Sữa         ┆ 2             │
│ Sữa         ┆ 1             │
│ Sữa         ┆ 2             │
│ Sữa         ┆ 0             │
│ Sữa         ┆ 0             │
└─────────────┴───────────────┘

In [7]:
customer_age_features_df = pl.read_parquet("./new-feature/customer_age_features.parquet")
customer_age_features_df = customer_age_features_df['customer_id', 'age_final']
customer_age_features_df.head()

shape: (5, 2)
┌─────────────┬───────────┐
│ customer_id ┆ age_final │
│ ---         ┆ ---       │
│ i32         ┆ f64       │
╞═════════════╪═══════════╡
│ 7296704     ┆ 11.533333 │
│ 3003052     ┆ null      │
│ 7611829     ┆ null      │
│ 241342      ┆ 10.6      │
│ 3733312     ┆ 12.666667 │
└─────────────┴───────────┘

In [8]:
customer_behavior_df = pl.read_parquet("./new-feature/customer_behavior.parquet")
# customer_behavior_df = customer_behavior_df['customer_id', 'buy_segment']
customer_behavior_df

shape: (2_442_306, 6)
┌─────────────┬───────────────────┬────────────┬───────────────────┬─────────────────┬─────────────┐
│ customer_id ┆ total_unique_cate ┆ total_days ┆ avg_categories_pe ┆ buy_segment_raw ┆ buy_segment │
│ ---         ┆ gories            ┆ ---        ┆ r_day             ┆ ---             ┆ ---         │
│ i32         ┆ ---               ┆ u32        ┆ ---               ┆ i32             ┆ i32         │
│             ┆ u32               ┆            ┆ f64               ┆                 ┆             │
╞═════════════╪═══════════════════╪════════════╪═══════════════════╪═════════════════╪═════════════╡
│ 7912392     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 7396997     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 7279939     ┆ 40                ┆ 25         ┆ 1.6               ┆ 2               ┆ 1           │
│ 690290      ┆ 2                 ┆ 2          ┆ 1.0               ┆ 0               ┆ 0           │
│ 6323569     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ …           ┆ …                 ┆ …          ┆ …                 ┆ …               ┆ …           │
│ 1599282     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 7105696     ┆ 13                ┆ 10         ┆ 1.3               ┆ 0               ┆ 0           │
│ 7413857     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 7150126     ┆ 2                 ┆ 2          ┆ 1.0               ┆ 0               ┆ 0           │
│ 4663267     ┆ 3                 ┆ 1          ┆ 3.0               ┆ 1               ┆ 2           │
└─────────────┴───────────────────┴────────────┴───────────────────┴─────────────────┴─────────────┘

In [20]:
customer_luxury_df = pl.read_parquet("./new-feature/customer_luxury.parquet")
customer_luxury_df = customer_luxury_df['customer_id', 'luxury_level']
customer_luxury_df.head()

shape: (5, 2)
┌─────────────┬──────────────┐
│ customer_id ┆ luxury_level │
│ ---         ┆ ---          │
│ i32         ┆ i32          │
╞═════════════╪══════════════╡
│ 3915079     ┆ 0            │
│ 335117      ┆ 0            │
│ 703093      ┆ 1            │
│ 4200016     ┆ 1            │
│ 2524669     ┆ 1            │
└─────────────┴──────────────┘

In [10]:
price_segment_df = pl.read_parquet("./new-feature/price_segment.parquet")
price_segment_df = price_segment_df['item_id', 'price_segment']
price_segment_df.head()

shape: (5, 2)
┌───────────────┬───────────────┐
│ item_id       ┆ price_segment │
│ ---           ┆ ---           │
│ str           ┆ i64           │
╞═══════════════╪═══════════════╡
│ 0502020000004 ┆ 0             │
│ 0010290040150 ┆ 0             │
│ 0008010000015 ┆ 0             │
│ 0020010000094 ┆ 1             │
│ 0020010000098 ┆ 1             │
└───────────────┴───────────────┘

In [11]:
top10_by_cat_month_df = pl.read_parquet("./new-feature/top10_by_cat_month.parquet")
# top10_by_cat_month_df = top10_by_cat_month_df['item_id', 'rank']
top10_by_cat_month_df.head()

shape: (5, 5)
┌─────────┬─────────────┬───────────────┬────────────┬──────┐
│ month   ┆ category_l1 ┆ item_id       ┆ total_sold ┆ rank │
│ ---     ┆ ---         ┆ ---           ┆ ---        ┆ ---  │
│ str     ┆ str         ┆ str           ┆ i32        ┆ u32  │
╞═════════╪═════════════╪═══════════════╪════════════╪══════╡
│ 2024-01 ┆ Babycare    ┆ 5950000000001 ┆ 17358      ┆ 1    │
│ 2024-01 ┆ Babycare    ┆ 0007160000082 ┆ 10646      ┆ 2    │
│ 2024-01 ┆ Babycare    ┆ 0007150000144 ┆ 10069      ┆ 3    │
│ 2024-01 ┆ Babycare    ┆ 0007150000031 ┆ 8871       ┆ 4    │
│ 2024-01 ┆ Babycare    ┆ 0203000000004 ┆ 8475       ┆ 5    │
└─────────┴─────────────┴───────────────┴────────────┴──────┘

In [7]:
fl=pl.read_parquet("/datastore/uittogether/LuuTru/Thanhld/CS116-DoAn/Phase-2/Pipeline-training3/Thanh/artifacts/stage2_train_new_item_rec.parquet")
# fl['brand_segment'].value_counts()
# fl

In [6]:
print(fl['label'].value_counts())
# print(fl['ui_recency_days'].value_counts())

shape: (2, 2)
┌───────┬──────────┐
│ label ┆ count    │
│ ---   ┆ ---      │
│ i64   ┆ u32      │
╞═══════╪══════════╡
│ 1     ┆ 118153   │
│ 0     ┆ 13865413 │
└───────┴──────────┘

In [8]:
fl

shape: (13_983_566, 18)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ customer_i ┆ item_id    ┆ stage1_ran ┆ stage1_sc ┆ … ┆ feat_log_ ┆ feat_baby ┆ feat_is_a ┆ label │
│ d          ┆ ---        ┆ k          ┆ ore       ┆   ┆ price     ┆ _age      ┆ ge_match  ┆ ---   │
│ ---        ┆ str        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64   │
│ str        ┆            ┆ i64        ┆ f64       ┆   ┆ f64       ┆ i64       ┆ i64       ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 8211116    ┆ 0042000000 ┆ 1          ┆ 0.0       ┆ … ┆ 12.476104 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 002        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8211116    ┆ 4950000000 ┆ 2          ┆ 0.0       ┆ … ┆ 12.861001 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 002        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8211116    ┆ 6697000000 ┆ 3          ┆ 0.0       ┆ … ┆ 10.491302 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 001        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8211116    ┆ 4950000000 ┆ 4          ┆ 0.0       ┆ … ┆ 13.49943  ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 001        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8211116    ┆ 0502020000 ┆ 5          ┆ 0.0       ┆ … ┆ 11.396403 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 042        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ 8119018    ┆ 2803000000 ┆ 186        ┆ 0.0       ┆ … ┆ 10.839601 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 010        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8119018    ┆ 2803000000 ┆ 187        ┆ 0.0       ┆ … ┆ 10.839601 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 011        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8119018    ┆ 2803000000 ┆ 188        ┆ 0.0       ┆ … ┆ 10.839601 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 012        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8119018    ┆ 2803000000 ┆ 189        ┆ 0.0       ┆ … ┆ 10.839601 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 013        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 8119018    ┆ 0029130000 ┆ 190        ┆ 0.0       ┆ … ┆ 11.211834 ┆ -1        ┆ 0         ┆ 0     │
│            ┆ 030        ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [4]:
import pickle

with open("/datastore/uittogether/LuuTru/Thanhld/CS116-DoAn/Phase-2/Pipeline-training3/Thanh/data/final_groundtruth.pkl", "rb") as f:
    data = pickle.load(f)

print(type(data))
print("Length:", len(data))

/tmp/ipykernel_1513552/2774588283.py:4: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data = pickle.load(f)

<class 'pandas.core.frame.DataFrame'>
Length: 644970

In [5]:
data

        customer_id                                            item_id
0           2337685                                    [0020010000305]
1           7934799                                    [0020010000438]
2           2052333  [3513000000064, 2403000000004, 3460000000018, ...
3           6548920                                    [6701000000004]
4            368770  [5420000000003, 5420000000002, 1371000000002, ...
...             ...                                                ...
644965      4588966  [2485000000005, 7028000000002, 0068000000077, ...
644966      5048510  [5420000000003, 1371000000007, 1371000000003, ...
644967      7747340      [0188000000001, 3390000000010, 0502020340032]
644968      6715064                                    [4327000000005]
644969      8126259                     [7170000000003, 7170000000002]

[644970 rows x 2 columns]

In [11]:
import pandas as pd
import numpy as np

In [12]:
df = load_groundtruth_pkl("/datastore/uittogether/LuuTru/Thanhld/CS116-DoAn/Phase-2/Pipeline-training3/Thanh/data/final_groundtruth.pkl")

Loading Ground Truth from: /datastore/uittogether/LuuTru/Thanhld/CS116-DoAn/Phase-2/Pipeline-training3/Thanh/data/final_groundtruth.pkl

/tmp/ipykernel_1513552/3544524365.py:9: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data = pickle.load(f)

   [DEBUG] Original Data Type: <class 'pandas.core.frame.DataFrame'>
   [INFO] Detected DataFrame with 644970 rows.
   [INFO] Detected aggregated items (List/Array). Exploding data...
   [INFO] Rows after explosion: 2665926
   [INFO] Grouping by user to create sets...
   [SUCCESS] Final Loaded Users: 644970
   [DEBUG SAMPLE] User 1000011: ['7055000000002', '29250010026', '44000000004'] ... (Total: 6)

In [13]:
df

{'1000011': {'1530000000011',
  '2760000000002',
  '2766000000004',
  '29250010026',
  '44000000004',
  '7055000000002'},
 '1000024': {'3775000000003'},
 '1000042': {'179000000021', '7000000000040'},
 '1000057': {'8000000045', '9000000002'},
 '1000066': {'2286000000002'},
 '1000070': {'2278000000028',
  '2746000000009',
  '2803000000010',
  '2803000000013',
  '4396000000001',
  '5492000000001',
  '6497000000004'},
 '1000101': {'20020000185',
  '203000000004',
  '2403000000001',
  '2609000000001',
  '2691000000001',
  '2700000000002',
  '3496000000050',
  '4455000000001',
  '4690000000001',
  '5050000000001',
  '5595000000002',
  '5950000000001',
  '6870000000005',
  '7080000289',
  '7321000000002'},
 '1000121': {'2006000000006', '2278000000036'},
 '1000130': {'1512000000004',
  '20010000296',
  '2482000000004',
  '4690000000001',
  '4950000000001',
  '5140000000009',
  '5140000000011',
  '5950000000001'},
 '1000132': {'2691000000001',
  '29120000028',
  '4467000000001',
  '4559000000004',
  '7176000000002'},
 '1000192': {'2861000000001', '7175000000002'},
 '1000198': {'2005000000004', '2109000000078', '2808000000001'},
 '1000214': {'1428000000001', '2484000000008', '6768000000003'},
 '1000263': {'1713000000002',
  '1920001360750',
  '204000000003',
  '2497000000003',
  '54000000010',
  '7024000000001'},
 '1000298': {'1512000000004',
  '203000000004',
  '5140000000003',
  '6699000000001',
  '6732000000001',
  '7000000000039'},
 '1000309': {'2578000000002'},
 '1000311': {'1370000000011',
  '20020000203',
  '20020000204',
  '20020000253',
  '2261000000004',
  '29040000036',
  '29080000003',
  '29080000004',
  '29080000005',
  '29120000066',
  '29250010001',
  '4680000000001',
  '4690000000001',
  '5427000000005',
  '5444000000008',
  '5444000000016'},
 '1000319': {'2261000000003',
  '2287000000002',
  '2415000000002',
  '29120000029',
  '4373000000001',
  '5444000000017',
  '5506000000004',
  '5599000000001',
  '6237000000002',
  '6438000000002',
  '6542000000001'},
 '1000326': {'11000000028', '6033000000063', '6609000000012', '7339000000003'},
 '1000336': {'29130000030'},
 '1000364': {'2517000000001', '4029000000007'},
 '1000366': {'1920001360752',
  '2261000000003',
  '2950000000002',
  '4690000000001',
  '4784000000003',
  '4869000000001',
  '5940000000004'},
 '1000374': {'20010000440'},
 '1000400': {'1774000000004',
  '1920001360752',
  '20020000185',
  '203000000004',
  '2414000000002',
  '2497000000002',
  '2596000000002',
  '2610000000004',
  '2872000000001'},
 '1000451': {'7176000000002'},
 '1000452': {'2005000000006', '2346000000152', '5358000000001'},
 '1000463': {'2707000000001', '6382000000004', '6382000000005'},
 '1000468': {'1920001360752',
  '2005000000004',
  '2005000000006',
  '2024000000011'},
 '1000470': {'1774000000004',
  '4895000000003',
  '6803000000004',
  '6827000000002',
  '6827000000003'},
 '1000485': {'1371000000006',
  '1735000000009',
  '20010000438',
  '20020000261',
  '2005000000006',
  '5420000000003',
  '6382000000002',
  '6426000000003',
  '7232000000002'},
 '1000513': {'136000000003'},
 '100058': {'4950000000001', '4950000000002'},
 '1000581': {'2573000000010',
  '2803000000013',
  '29120000029',
  '29120000048',
  '29250010002',
  '5538000000001',
  '6501000000007',
  '7163000000002',
  '7163000000004',
  '9000000002'},
 '1000587': {'1512000000004',
  '20020000185',
  '2005000000004',
  '2005000000006',
  '2027000000003',
  '2202000000006',
  '2287000910002',
  '2803000000010',
  '2803000000012',
  '29250010003',
  '4400000000005',
  '5481000000002',
  '5843000000015',
  '6382000000002',
  '7150000143'},
 '1000597': {'2278000000029'},
 '1000673': {'6548000000002', '6857000000001'},
 '1000679': {'1346000000003',
  '1370000000013',
  '1455000000004',
  '1728000000030',
  '1771000000001',
  '1778000000001',
  '20020000104',
  '20020000170',
  '20020000201',
  '20020000202',
  '20020000253',
  '2027000000001',
  '2231000000028',
  '2793000000003',
  '2803000000013',
  '29010030006',
  '29110000039',
  '29120000029',
  '29120000031',
  '29120000046',
  '29130000029',
  '3286000000004',
  '3774000000003',
  '4697000000002',
  '5029000000010',
  '5506000000007',
  '5918000000005',
  '6472000000004',
  '6697000000002',
  '6812000000001',
  '70000000031',
  '7039000000002',
  '7167000000002',
  '7167000000005'},
 '1000687': {'171000000003',
  '212000000012',
  '2286000000006',
  '3875000000001',
  '4690000000001',
  '4783000000003'},
 '1000707': {'2286000000009', '2287000910002'},
 '1000730': {'4876000000004',
  '5444000000016',
  '5537000000002',
  '5537000000012',
  '5836000000004',
  '6847000000004',
  '7115000000005',
  '7163000000002'},
 '1000743': {'1371000000001',
  '1371000000002',
  '5420000000003',
  '5492000000001',
  '6665000000002',
  '6665000000004',
  '6889000000005'},
 '1000760': {'1371000000001',
  '1371000000004',
  '1371000000005',
  '29130000030',
  '4690000000001',
  '5497000000005',
  '7170000000002'},
 '1000807': {'2005000000006',
  '2030000000007',
  '4690000000001',
  '6697000000003',
  '6701000000004'},
 '1000808': {'6768000000005'},
 '1000823': {'1920001360752',
  '29120000029',
  '4690000000001',
  '4952000000001',
  '6070000000001',
  '6768000000005'},
 '1000884': {'20120000014', '5902000000002'},
 '1000889': {'2287000910001'},
 '1000891': {'3788000000011', '54000000007', '55000000001', '6040000478'},
 '1000919': {'1952000000016', '5358000000002'},
 '1000957': {'6768000000003'},
 '1000970': {'1920001360752',
  '2044000000180',
  '2044000000226',
  '2610000000008',
  '2700000000001',
  '2803000000013',
  '29120000066',
  '3880000000002',
  '4603024000001',
  '4690000000001',
  '5950000000001',
  '7090000157',
  '7115000000003'},
 '1000997': {'5856000000001', '6477000000006'},
 '1001015': {'2678000000002',
  '5405000000002',
  '6767000000003',
  '7339000000003'},
 '1001056': {'1728000000031',
  '2231000000029',
  '2231000000030',
  '3513000000072',
  '3953000000665',
  '4355000000001',
  '4690000000001',
  '6617000000047',
  '6768000000004',
  '7090000359',
  '7228000000016'},
 '1001082': {'1771000000001', '6048000000023'},
 '1001131': {'20010000385'},
 '1001137': {'6768000000004'},
 '1001180': {'2520000000001'},
 '1001228': {'20020000185'},
 '1001229': {'1370000000011',
  '1371000000004',
  '1371000000006',
  '20020000169',
  '20020000170',
  '20020000172',
  '20020000173',
  '20020000203',
  '2044000000132',
  '2202000000002',
  '2202000000006',
  '29080000003',
  '29080000004',
  '29080000007',
  '3286000000004',
  '4783000000009',
  '4784000000003',
  '5006000000011',
  '5420000000002',
  '5420000000003',
  '5427000000003',
  '5427000000004',
  '5437000000002',
  '5506000000003',
  '5506000000005',
  '5506000000007',
  '5617000000002',
  '5868000000001',
  '5952000000001',
  '6501000000004',
  '6501000000007',
  '6792000000002',
  '6847000000002',
  '6847000000003',
  '6847000000004',
  '7167000000002',
  '7167000000003',
  '7167000000004',
  '7167000000005'},
 '1001263': {'1920001360752',
  '2231000000030',
  '3817000000003',
  '6677000000014',
  '6697000000003'},
 '1001292': {'1396000000018',
  '2707000000001',
  '2760000000001',
  '4690000000001',
  '5373000000006',
  '6346000000005',
  '7090000158',
  '7161000000001',
  '7228000000019'},
 '1001302': {'20010000305',
  '2158000000001',
  '2506000000003',
  '4603024000001',
  '5589000000003',
  '5918000000002'},
 '1001325': {'2202000000008', '2482000000004'},
 '1001441': {'7090000359'},
 '1001453': {'1396000000017',
  '1452000000007',
  '20010000440',
  '29110000039',
  '29250010001',
  '5537000000007',
  '6847000000002',
  '6847000000003',
  '6847000000004',
  '7092000000006'},
 '1001466': {'1668000000004', '2584000000001'},
 '1001500': {'4178000000008',
  '4280000000033',
  '5950000000001',
  '6730000000003',
  '6767000000002',
  '6768000000002'},
 '1001510': {'2700000000002'},
 '1001513': {'1764000000002',
  '2265000000022',
  '2603000000001',
  '4600000000001',
  '6548000000002'},
 '1001518': {'1442000000001',
  '1771000000001',
  '29110000039',
  '4777000000001',
  '4877000000003',
  '5395000000002',
  '5488000000007',
  '5849000000002',
  '5849000000003',
  '5849000000004',
  '5918000000006',
  '6847000000002',
  '6847000000003',
  '7150000144'},
 '1001520': {'29140000027', '7170000060'},
 '1001539': {'3773000000004', '6766000000003'},
 '1001560': {'6768000000004', '7228000000022'},
 '1001575': {'1370000000011',
  '1442000000003',
  '2803000000010',
  '2803000000011',
  '2803000000012',
  '2803000000013',
  '29080000003',
  '29080000004',
  '29080000007',
  '3880000000001',
  '4690000000001',
  '5506000000003',
  '6665000000004'},
 '1001592': {'1920001360752',
  '2610000000008',
  '4603024000002',
  '4684000000001',
  '6054000000028',
  '6766000000003',
  '7090000158'},
 '1001625': {'2265000000024', '4690000000001'},
 '1001666': {'212000000012',
  '2285000000006',
  '5856000000001',
  '7150000144',
  '7170000071'},
 '1001672': {'20010000305',
  '2803000000012',
  '2803000000013',
  '4559000000004',
  '6268000000005'},
 '1001701': {'6768000000005'},
 '1001739': {'2260000000001', '2261000000002', '5856000000001'},
 '1001754': {'1215000000002',
  '2793000000004',
  '2803000000013',
  '2808000000001',
  '7161000000001'},
 '1001794': {'1796000000003'},
 '1001830': {'1920001360752',
  '2044000000156',
  '41000000028',
  '4466000000002',
  '4466000000005',
  '4584000000002',
  '4900000000001',
  '54000000010',
  '6346000000003',
  '6545000000002',
  '6545000000005',
  '6870000000005',
  '7039000000002',
  '7360000005'},
 '1001832': {'1371000000001',
  '1371000000004',
  '2803000000011',
  '3774000000003',
  '7257000000003'},
 '1001846': {'42000000003', '4294000000014'},
 '1001919': {'1512000000004'},
 '1001996': {'7176000000002'},
 '1002020': {'2578000000004', '29130000029'},
 '1002027': {'1920001360752',
  '2017000000035',
  '4003000000037',
  '4050000000010',
  '5836000000002',
  '5858000000001',
  '6798000000001',
  '7242000000002'},
 '1002059': {'20020000264', '20020000265', '6792000000004', '7176000000002'},
 '1002065': {'4396000000002', '4467000000002'},
 '1002067': {'2231000000013'},
 '1002077': {'4783000000009', '4784000000001'},
 '1002124': {'2265000000024'},
 '1002129': {'2024000000011',
  '2231000000013',
  '6501000000006',
  '6501000000007',
  '6697000000004',
  '7170000060'},
 '1002135': {'2260000000001',
  '2672000000004',
  '29130000030',
  '5849000000004',
  '5920000000003'},
 '1002136': {'2231000000029',
  '4600000000001',
  '5949000000013',
  '7175000000002'},
 '1002138': {'2155000000104', '29120000029', '29120000031', '6849000000003'},
 '1002182': {'136000000003',
  '1771000000001',
  '3944000000452',
  '3953000000362'},
 '1002193': {'2014000000003', '2030000000007', '6679000000005'},
 '100220': {'2444000000001', '54000000012', '6768000000004', '6768000000005'},
 '1002207': {'2610000000004', '2707000000001', '5836000000006'},
 '1002208': {'6768000000005'},
 '1002209': {'6700000000001'},
 '1002218': {'2278000000029'},
 '100224': {'20020000185',
  '2259000000002',
  '2276000000009',
  '2278000000033',
  '2872000000001'},
 '1002274': {'175000000007',
  '175000000008',
  '20020000265',
  '7000000000028',
  '7000000000035'},
 '1002316': {'1512000000004', '2278000000035'},
 '1002355': {'28020000001'},
 '1002364': {'2027000000003',
  '4690000000001',
  '4869000000001',
  '956000000106'},
 '1002367': {'2541000000002',
  '3491000000010',
  '3491000000031',
  '3494000000064'},
 '1002393': {'1434000000013', '2231000000029', '5599000000001'},
 '1002397': {'11000000018',
  '179000000021',
  '4013000000056',
  '5029000000010',
  '7352000000003'},
 '1002411': {'4690000000001', '5471000000006', '5492000000001'},
 '1002436': {'2414000000002'},
 '1002450': {'29040000008',
  '3266000000004',
  '3912000000002',
  '5117000000002',
  '6501000000004'},
 '1002458': {'7176000000004'},
 '1002464': {'29040000019'},
 '1002529': {'4178000000008'},
 '1002539': {'2577000000004'},
 '100256': {'2188000000026', '3951000000295', '3951000000300'},
 '1002561': {'4603024000002'},
 '1002564': {'195000000002', '42000000001'},
 '1002565': {'2265000000025',
  '4690000000001',
  '502100340015',
  '5137000000002',
  '5576000000002',
  '5951000000003',
  '7106000000003',
  '7106000000004',
  '7106000000005'},
 '1002583': {'2484000000008', '3051000000002'},
 '100260': {'203000000002',
  '2286000000001',
  '6054000000030',
  '6767000000002',
  '6767000000003',
  '6902000000002',
  '952000000098'},
 '1002648': {'1386000000008', '2019000000001', '2489000000002'},
 '1002658': {'1771000000002',
  '1774000000004',
  '20020000268',
  '2265000000024',
  '54000000007',
  '6490000000001',
  '6697000000003',
  '6909000000001',
  '7140000018',
  '9000000002'},
 '1002741': {'7176000000002'},
 '1002765': {'1952000000016',
  '29020010001',
  '29130000029',
  '4279000000126',
  '4690000000001',
  '5140000000010',
  '5140000000011',
  '5388000000001'},
 '1002767': {'6426000000001'},
 '1002779': {'2700000000002', '29250010001', '4603024000002', '5503000000003'},
 '1002784': {'20010000305', '2019000000001', '2707000000001', '7160000078'},
 '1002795': {'3502000000006',
  '4392000000002',
  '4690000000001',
  '7228000000017',
  '7228000000021',
  '8020000195'},
 '1002802': {'2706000000001',
  '4399000000001',
  '4690000000001',
  '6498000000005',
  '6768000000005'},
 '1002844': {'20010000305',
  '4603024000002',
  '502040340038',
  '5918000000005',
  '7284000000001'},
 '1002861': {'2017000000035',
  '2044000000067',
  '2803000000012',
  '4294000000062',
  '5506000000003',
  '5951000000003'},
 '1002883': {'2265000000025', '2506000000003', '3787000000014'},
 '1002886': {'1952000000016', '20120000033', '3789000000001', '4690000000001'},
 '1002896': {'29140000028', '4594000000004'},
 '1002940': {'2520000000002'},
 '1002955': {'2006000000006',
  '3324000000368',
  '502100340019',
  '6034000000080'},
 '1002957': {'2609000000001',
  '4402000000001',
  '5200000000001',
  '6548000000002',
  '8000000040'},
 '1002958': {'7150000144'},
 '100300': {'4603024000001', '5918000000005'},
 '1003001': {'2700000000001', '3286000000004'},
 '1003022': {'2287000890001', '2363000000001'},
 '1003091': {'29250010001',
  '3773000000003',
  '4006000000045',
  '4467000000001',
  '4467000000002',
  '4690000000001',
  '6847000000003',
  '6847000000004',
  '6849000000005'},
 '1003092': {'2260000000001', '3773000000004'},
 '1003110': {'2744000000008', '29140000031', '7176000000004', '7339000000003'},
 '1003115': {'135000000001',
  '136000000003',
  '175000000007',
  '175000000011',
  '1774000000003',
  '20010000210',
  '2278000000019',
  '2584000000002',
  '3269000000001',
  '3494000000063',
  '3503000000010',
  '3798000000009',
  '7150000031',
  '9000000002'},
 '1003126': {'2110000000019', '29020010001', '5358000000001', '5388000000001'},
 '1003152': {'2265000000024', '7228000000022'},
 '1003153': {'136000000002',
  '1774000000004',
  '2123000000014',
  '4268000000069',
  '4690000000001',
  '5076000000002',
  '5492000000001',
  '5902000000002',
  '5950000000001',
  '6040000180',
  '6431000000001',
  '6767000000002',
  '6870000000004',
  '7010000814'},
 '1003158': {'502100340015'},
 '1003183': {'1308000000003',
  '1920001360752',
  '20010000188',
  '2798000000001',
  '3051000000002',
  '5140000000011',
  '7162000000002',
  '7162000000004'},
 '1003207': {'20010000305'},
 '1003231': {'1434000000002',
  '1434000000012',
  '1452000000008',
  '20020000185',
  '2024000000010',
  '29040000008',
  '29250010001',
  '3875000000001',
  '6792000000004',
  '6827000000003'},
 '1003249': {'2491000000002'},
 '1003320': {'175000000007',
  '175000000009',
  '1764000000001',
  '1920001360752',
  '1952000000016',
  '20010000438',
  '20020000185',
  '2263000000017',
  '29130000029',
  '3773000000004',
  '3774000000003',
  '4013000000066',
  '4027000000043',
  '4467000000002',
  '4467000000003',
  '5140000000010',
  '54000000011',
  '5503000000003',
  '5856000000001',
  '5920000000003',
  '6767000000003',
  '6768000000003',
  '6768000000004',
  '68000000033',
  '68000000057',
  '68000000160',
  '69000000001',
  '70000000006',
  '7090000157',
  '7090000252',
  '7162000000002',
  '7228000000022',
  '7360000005',
  '85000000068',
  '919000000120'},
 '1003330': {'29130000028', '29130000030', '4690000000001'},
 '1003364': {'2505000000003',
  '2793000000004',
  '29110000036',
  '5489000000005',
  '5617000000001',
  '6382000000002',
  '7160000078'},
 '1003404': {'20020000185'},
 '1003434': {'2707000000001',
  '4006000000044',
  '5471000000019',
  '6033000000049',
  '6469000000002',
  '954000000078'},
 '1003444': {'2584000000001', '4690000000001'},
 '1003467': {'1920001360752',
  '4600000000001',
  '6382000000004',
  '6498000000005',
  '7176000000002'},
 '1003512': {'502040340038', '5444000000021', '5918000000003'},
 '1003561': {'20010000305', '2024000000011', '2155000000057', '2793000000003'},
 '1003567': {'20010000438'},
 '1003583': {'5370000000001', '5373000000006', '5389000000002'},
 '1003607': {'2863000000006'},
 '1003689': {'1428000000001',
  '2202000000006',
  '2872000000001',
  '4279000000126',
  '4364000000002',
  '5115000000001',
  '5444000000016',
  '5920000000002',
  '7092000000012',
  '7140000002'},
 '1003695': {'1920001360752',
  '2027000000003',
  '2044000000135',
  '2202000000006',
  '2278000000038',
  '2584000000003',
  '4869000000002',
  '5137000000001',
  '5843000000015',
  '6382000000002',
  '7322000000001'},
 '1003718': {'2746000000009',
  '4877000000005',
  '4895000000002',
  '5595000000002',
  '5598000000003',
  '6501000000004',
  '6501000000006',
  '6667000000002',
  '7210000000001'},
 '1003720': {'1920001360752',
  '2155000000105',
  '2482000000003',
  '2483000000004',
  '29110000036',
  '29120000031',
  '2971000000001',
  '4603024000001',
  '5497000000005',
  '6847000000004',
  '6848000000003',
  '7115000000004',
  '7162000000003'},
 '1003760': {'2603000000002',
  '4378000000001',
  '4402000000001',
  '4603024000001',
  '76000000040'},
 '1003795': {'29130000030', '7210000000001'},
 '1003800': {'2408000000010'},
 '1003880': {'5595000000001'},
 '1003893': {'20010000440', '5739000000002'},
 '1003918': {'136000000003'},
 '1003928': {'2700000000002',
  '4680000000001',
  '5510000000002',
  '5537000000012',
  '5537000000014',
  '5868000000001',
  '6435000000003'},
 '1003952': {'29110000039', '3047000000002', '3052000000001', '4895000000001'},
 '1003969': {'2006000000006',
  '2027000000003',
  '29250010003',
  '4296000000054',
  '4361000000001',
  '4525000000003',
  '4869000000002',
  '5537000000007',
  '7070000406'},
 '1003970': {'3266000000006'},
 '1003978': {'1438000000001', '29140000027', '5481000000001', '7380000024'},
 '1003999': {'1370000000012',
  '1370000000013',
  '1370000000014',
  '1371000000003',
  '180000000011',
  '2014000000005',
  '5918000000003',
  '6847000000003'},
 '1004014': {'1446000000001',
  '1771000000001',
  '2691000000001',
  '2803000000012',
  '2803000000013',
  '4680000000002',
  '4690000000001',
  '5029000000011',
  '5444000000021',
  '5538000000001',
  '5951000000002',
  '6501000000006',
  '6501000000007',
  '68000000027',
  '7010000290'},
 '1004026': {'3821000000001'},
 '1004042': {'6685000000003'},
 '1004053': {'2155000000122', '4296000000054', '4690000000001'},
 '1004078': {'2408000000010'},
 '1004081': {'2485000000005'},
 '1004082': {'5836000000004', '5836000000006'},
 '1004137': {'6768000000005'},
 '1004140': {'1525000000001',
  '2202000000006',
  '2344000000063',
  '6812000000001',
  '6812000000002',
  '6812000000005'},
 '1004144': {'1920001360750',
  '5858000000003',
  '6469000000004',
  '7337000000003'},
 '1004148': {'4603024000002'},
 '1004163': {'4680000000002', '4950000000001'},
 '1004184': {'2265000000027', '4603024000002'},
 '1004200': {'2264000000003', '2264000000005'},
 '1004211': {'20010000440', '20020000185', '6072000000004'},
 '1004228': {'5856000000001', '5857000000001'},
 '1004239': {'2017000000035'},
 '1004244': {'1796000000002', '1796000000003', '2484000000006'},
 '1004267': {'29120000029', '29130000021', '29130000030'},