# Download các thư viện cần thiết

In [2]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Tạo hàm để đọc file parquet (đọc các file parquet - data sau khi được processed)

In [2]:
def read_parquet_user(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    user_chunk_files = [file for file in files if 'user_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    user_chunk_df = pl.concat([pl.read_parquet(file) for file in user_chunk_files]) if user_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return user_chunk_df

In [3]:
def read_parquet_item(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    item_chunk_files = [file for file in files if 'item_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return item_chunk_df

In [4]:
def read_parquet_transaction(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    purchase_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    purchase_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_chunk_files]) if purchase_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return purchase_chunk_df

# Tạo hàm lưu file parquet sau mỗi task

In [4]:
brand_segment_df = pl.read_parquet("./Phase-2/new-feature/brand_segment.parquet")
brand_segment_df.head()

shape: (5, 2)
┌─────────────┬───────────────┐
│ category_l1 ┆ brand_segment │
│ ---         ┆ ---           │
│ str         ┆ i64           │
╞═════════════╪═══════════════╡
│ Sữa         ┆ 2             │
│ Sữa         ┆ 1             │
│ Sữa         ┆ 2             │
│ Sữa         ┆ 0             │
│ Sữa         ┆ 0             │
└─────────────┴───────────────┘

In [8]:
customer_age_features_df = pl.read_parquet("./Phase-2/new-feature/customer_age_features.parquet")
customer_age_features_df = customer_age_features_df['customer_id', 'age_final']
customer_age_features_df.head()

shape: (5, 2)
┌─────────────┬───────────┐
│ customer_id ┆ age_final │
│ ---         ┆ ---       │
│ i32         ┆ f64       │
╞═════════════╪═══════════╡
│ 7296704     ┆ 11.533333 │
│ 3003052     ┆ null      │
│ 7611829     ┆ null      │
│ 241342      ┆ 10.6      │
│ 3733312     ┆ 12.666667 │
└─────────────┴───────────┘

In [10]:
customer_behavior_df = pl.read_parquet("./Phase-2/new-feature/customer_behavior.parquet")
customer_behavior_df = customer_behavior_df['customer_id', 'buy_segment']
customer_behavior_df

shape: (2_442_306, 2)
┌─────────────┬─────────────┐
│ customer_id ┆ buy_segment │
│ ---         ┆ ---         │
│ i32         ┆ i32         │
╞═════════════╪═════════════╡
│ 7912392     ┆ 0           │
│ 7396997     ┆ 0           │
│ 7279939     ┆ 1           │
│ 690290      ┆ 0           │
│ 6323569     ┆ 0           │
│ …           ┆ …           │
│ 1599282     ┆ 0           │
│ 7105696     ┆ 0           │
│ 7413857     ┆ 0           │
│ 7150126     ┆ 0           │
│ 4663267     ┆ 2           │
└─────────────┴─────────────┘

In [12]:
customer_luxury_df = pl.read_parquet("./Phase-2/new-feature/customer_luxury.parquet")
customer_luxury_df = customer_luxury_df['customer_id', 'luxury_level']
customer_luxury_df.head()

shape: (5, 2)
┌─────────────┬──────────────┐
│ customer_id ┆ luxury_level │
│ ---         ┆ ---          │
│ i32         ┆ i32          │
╞═════════════╪══════════════╡
│ 3915079     ┆ 0            │
│ 335117      ┆ 0            │
│ 703093      ┆ 1            │
│ 4200016     ┆ 1            │
│ 2524669     ┆ 1            │
└─────────────┴──────────────┘

In [16]:
price_segment_df = pl.read_parquet("./Phase-2/new-feature/price_segment.parquet")
price_segment_df = price_segment_df['item_id', 'price_segment']
price_segment_df.head()

shape: (5, 2)
┌───────────────┬───────────────┐
│ item_id       ┆ price_segment │
│ ---           ┆ ---           │
│ str           ┆ i64           │
╞═══════════════╪═══════════════╡
│ 0502020000004 ┆ 0             │
│ 0010290040150 ┆ 0             │
│ 0008010000015 ┆ 0             │
│ 0020010000094 ┆ 1             │
│ 0020010000098 ┆ 1             │
└───────────────┴───────────────┘

In [18]:
top10_by_cat_month_df = pl.read_parquet("./Phase-2/new-feature/top10_by_cat_month.parquet")
top10_by_cat_month_df = top10_by_cat_month_df['item_id', 'rank']
top10_by_cat_month_df.head()

shape: (5, 2)
┌───────────────┬──────┐
│ item_id       ┆ rank │
│ ---           ┆ ---  │
│ str           ┆ u32  │
╞═══════════════╪══════╡
│ 5950000000001 ┆ 1    │
│ 0007160000082 ┆ 2    │
│ 0007150000144 ┆ 3    │
│ 0007150000031 ┆ 4    │
│ 0203000000004 ┆ 5    │
└───────────────┴──────┘