# Download các thư viện cần thiết

In [1]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Tạo hàm để đọc file parquet (đọc các file parquet - data sau khi được processed)

In [2]:
def read_parquet_user(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    user_chunk_files = [file for file in files if 'user_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    user_chunk_df = pl.concat([pl.read_parquet(file) for file in user_chunk_files]) if user_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return user_chunk_df

In [3]:
def read_parquet_item(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    item_chunk_files = [file for file in files if 'item_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return item_chunk_df

In [4]:
def read_parquet_transaction(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    purchase_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    purchase_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_chunk_files]) if purchase_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return purchase_chunk_df

# Tạo hàm lưu file parquet sau mỗi task

In [5]:
def split_and_save_parquet(df, num_files, output_dir, type):
    """
    Tách DataFrame thành nhiều file Parquet và lưu vào thư mục đích.
    
    :param df: DataFrame cần tách
    :param num_files: Số lượng file Parquet muốn tách
    :param output_dir: Thư mục lưu các file Parquet
    """
    # Đảm bảo thư mục tồn tại
    os.makedirs(output_dir, exist_ok=True)
    
    # Tính số dòng mỗi file sẽ có
    num_rows = df.height
    rows_per_file = num_rows // num_files

    # Tách DataFrame thành các phần và lưu mỗi phần vào một file Parquet
    for i in range(num_files):
        start_row = i * rows_per_file
        # Đảm bảo phần cuối cùng sẽ chứa tất cả các dòng còn lại
        end_row = (i + 1) * rows_per_file if i < num_files - 1 else num_rows
        
        # Tách phần DataFrame
        split_df = df[start_row:end_row]
        
        # Lưu phần DataFrame vào file .parquet
        file_path = os.path.join(output_dir, f"sale_pers.{type}_chunk_{i}.parquet")
        split_df.write_parquet(file_path)
        print(f"Đã lưu file: {file_path}")

# Chuẩn bị dữ liệu

In [6]:
user = read_parquet_user("./preprocessed-dataset")
user.head()

shape: (5, 11)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ gender ┆ province   ┆ membershi ┆ … ┆ install_d ┆ user_age_ ┆ days_sinc ┆ days_sinc │
│ d          ┆ ---    ┆ ---        ┆ p         ┆   ┆ atetime   ┆ days      ┆ e_install ┆ e_last_sy │
│ ---        ┆ str    ┆ str        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ nc        │
│ i32        ┆        ┆            ┆ str       ┆   ┆ date      ┆ f64       ┆ f64       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 6359043    ┆ male   ┆ Kon Tum    ┆ Standard  ┆ … ┆ 2023-04-0 ┆ 905.16172 ┆ 905.91709 ┆ 76.414299 │
│            ┆        ┆            ┆           ┆   ┆ 9         ┆ 6         ┆ 1         ┆           │
│ 6359044    ┆ male   ┆ Bình Thuận ┆ Gold      ┆ … ┆ 2023-04-0 ┆ 905.16134 ┆ 905.91709 ┆ 76.414299 │
│            ┆        ┆            ┆           ┆   ┆ 9         ┆ 4         ┆ 1         ┆           │
│ 6359046    ┆ female ┆ Hồ Chí     ┆ Standard  ┆ … ┆ 2023-04-0 ┆ 905.16102 ┆ 905.91709 ┆ 76.414299 │
│            ┆        ┆ Minh       ┆           ┆   ┆ 9         ┆ 4         ┆ 1         ┆           │
│ 6359051    ┆ female ┆ Nghệ An    ┆ Standard  ┆ … ┆ 2023-04-0 ┆ 905.16025 ┆ 905.91709 ┆ 76.414299 │
│            ┆        ┆            ┆           ┆   ┆ 9         ┆ 9         ┆ 1         ┆           │
│ 6359055    ┆ male   ┆ Đồng Nai   ┆ Standard  ┆ … ┆ 2023-04-0 ┆ 905.15972 ┆ 905.91709 ┆ 76.414299 │
│            ┆        ┆            ┆           ┆   ┆ 9         ┆ 4         ┆ 1         ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
transaction = read_parquet_transaction("./preprocessed-dataset")
transaction.head()

shape: (5, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ price     ┆ quantity ┆ customer_ ┆ … ┆ discount  ┆ list_pric ┆ category_ ┆ discount_ │
│ ---       ┆ ---       ┆ ---      ┆ id        ┆   ┆ ---       ┆ e         ┆ l2        ┆ rate      │
│ str       ┆ decimal[3 ┆ i32      ┆ ---       ┆   ┆ decimal[3 ┆ ---       ┆ ---       ┆ ---       │
│           ┆ 8,4]      ┆          ┆ i32       ┆   ┆ 8,4]      ┆ decimal[3 ┆ str       ┆ decimal[3 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8,4]      ┆           ┆ 8,4]      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 259600000 ┆ 296000.00 ┆ 1        ┆ 7627794   ┆ … ┆ 149000.00 ┆ 445000.00 ┆ Moony     ┆ 0.3348    │
│ 0003      ┆ 00        ┆          ┆           ┆   ┆ 00        ┆ 00        ┆           ┆           │
│ 151200000 ┆ 274349.00 ┆ 1        ┆ 7367484   ┆ … ┆ 20651.000 ┆ 295000.00 ┆ TPCN cho  ┆ 0.0700    │
│ 0004      ┆ 00        ┆          ┆           ┆   ┆ 0         ┆ 00        ┆ bé        ┆           │
│ 553700000 ┆ 70562.000 ┆ 1        ┆ 4795945   ┆ … ┆ 4438.0000 ┆ 75000.000 ┆ Snack ăn  ┆ 0.0592    │
│ 0015      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ dặm       ┆           │
│ 464400000 ┆ 58240.000 ┆ 4        ┆ 7253028   ┆ … ┆ 23040.000 ┆ 65000.000 ┆ Caryn     ┆ 0.1040    │
│ 0001      ┆ 0         ┆          ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│ 270000000 ┆ 61750.000 ┆ 1        ┆ 7681758   ┆ … ┆ 3250.0000 ┆ 65000.000 ┆ Khăn khô  ┆ 0.0500    │
│ 0002      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
item = read_parquet_item("./preprocessed-dataset")
item.head()

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ item_type ┆ descripti ┆ gender_ta ┆ age_grou │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ ---       ┆ on_new    ┆ rget_fina ┆ p_final  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ l         ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Từ 9M    │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│ 001029004 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Bộ quần   ┆ Không xác ┆ Bé Gái    ┆ Từ 36M   │
│ 0150      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ áo        ┆ định      ┆           ┆          │
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ 0-12M    │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ ["Từ     │
│ 0094      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ 4M",     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "3M-6M", │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "12-36M" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ 12-36M   │
│ 0098      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ định      ┆ định      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Training Stage 1